import java.util.function.ToIntFunction;

public class bvs {
	public static final bvr a = a("air", new buu(cfi.c.a(cxd.a).a().f().g()));
	public static final bvr b = a("stone", new bvr(cfi.c.a(cxd.H, cxe.m).h().a(1.5F, 6.0F)));
	public static final bvr c = a("granite", new bvr(cfi.c.a(cxd.H, cxe.l).h().a(1.5F, 6.0F)));
	public static final bvr d = a("polished_granite", new bvr(cfi.c.a(cxd.H, cxe.l).h().a(1.5F, 6.0F)));
	public static final bvr e = a("diorite", new bvr(cfi.c.a(cxd.H, cxe.p).h().a(1.5F, 6.0F)));
	public static final bvr f = a("polished_diorite", new bvr(cfi.c.a(cxd.H, cxe.p).h().a(1.5F, 6.0F)));
	public static final bvr g = a("andesite", new bvr(cfi.c.a(cxd.H, cxe.m).h().a(1.5F, 6.0F)));
	public static final bvr h = a("polished_andesite", new bvr(cfi.c.a(cxd.H, cxe.m).h().a(1.5F, 6.0F)));
	public static final bvr i = a("grass_block", new bye(cfi.c.a(cxd.s).d().d(0.6F).a(cbh.c)));
	public static final bvr j = a("dirt", new bvr(cfi.c.a(cxd.r, cxe.l).d(0.5F).a(cbh.b)));
	public static final bvr k = a("coarse_dirt", new bvr(cfi.c.a(cxd.r, cxe.l).d(0.5F).a(cbh.b)));
	public static final bvr l = a("podzol", new cbe(cfi.c.a(cxd.r, cxe.J).d(0.5F).a(cbh.b)));
	public static final bvr m = a("cobblestone", new bvr(cfi.c.a(cxd.H).h().a(2.0F, 6.0F)));
	public static final bvr n = a("oak_planks", new bvr(cfi.c.a(cxd.x, cxe.o).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr o = a("spruce_planks", new bvr(cfi.c.a(cxd.x, cxe.J).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr p = a("birch_planks", new bvr(cfi.c.a(cxd.x, cxe.d).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr q = a("jungle_planks", new bvr(cfi.c.a(cxd.x, cxe.l).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr r = a("acacia_planks", new bvr(cfi.c.a(cxd.x, cxe.q).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr s = a("dark_oak_planks", new bvr(cfi.c.a(cxd.x, cxe.B).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr t = a("oak_sapling", new car(new cex(), cfi.c.a(cxd.e).a().d().c().a(cbh.c)));
	public static final bvr u = a("spruce_sapling", new car(new cey(), cfi.c.a(cxd.e).a().d().c().a(cbh.c)));
	public static final bvr v = a("birch_sapling", new car(new ceu(), cfi.c.a(cxd.e).a().d().c().a(cbh.c)));
	public static final bvr w = a("jungle_sapling", new car(new cew(), cfi.c.a(cxd.e).a().d().c().a(cbh.c)));
	public static final bvr x = a("acacia_sapling", new car(new cet(), cfi.c.a(cxd.e).a().d().c().a(cbh.c)));
	public static final bvr y = a("dark_oak_sapling", new car(new cev(), cfi.c.a(cxd.e).a().d().c().a(cbh.c)));
	public static final bvr z = a("bedrock", new bvr(cfi.c.a(cxd.H).a(-1.0F, 3600000.0F).f().a(bvs::a)));
	public static final bvr A = a("water", new bze(cxb.c, cfi.c.a(cxd.i).a().d(100.0F).f()));
	public static final bvr B = a("lava", new bze(cxb.e, cfi.c.a(cxd.k).a().d().d(100.0F).a(cfj -> 15).f()));
	public static final bvr C = a("sand", new caq(14406560, cfi.c.a(cxd.u, cxe.d).d(0.5F).a(cbh.i)));
	public static final bvr D = a("red_sand", new caq(11098145, cfi.c.a(cxd.u, cxe.q).d(0.5F).a(cbh.i)));
	public static final bvr E = a("gravel", new byg(cfi.c.a(cxd.u, cxe.m).d(0.6F).a(cbh.b)));
	public static final bvr F = a("gold_ore", new bzu(cfi.c.a(cxd.H).h().a(3.0F, 3.0F)));
	public static final bvr G = a("iron_ore", new bzu(cfi.c.a(cxd.H).h().a(3.0F, 3.0F)));
	public static final bvr H = a("coal_ore", new bzu(cfi.c.a(cxd.H).h().a(3.0F, 3.0F)));
	public static final bvr I = a("nether_gold_ore", new bzu(cfi.c.a(cxd.H, cxe.K).h().a(3.0F, 3.0F).a(cbh.T)));
	public static final bvr J = a("oak_log", a(cxe.o, cxe.J));
	public static final bvr K = a("spruce_log", a(cxe.J, cxe.B));
	public static final bvr L = a("birch_log", a(cxe.d, cxe.p));
	public static final bvr M = a("jungle_log", a(cxe.l, cxe.J));
	public static final bvr N = a("acacia_log", a(cxe.q, cxe.m));
	public static final bvr O = a("dark_oak_log", a(cxe.B, cxe.B));
	public static final bvr P = a("stripped_spruce_log", a(cxe.J, cxe.J));
	public static final bvr Q = a("stripped_birch_log", a(cxe.d, cxe.d));
	public static final bvr R = a("stripped_jungle_log", a(cxe.l, cxe.l));
	public static final bvr S = a("stripped_acacia_log", a(cxe.q, cxe.q));
	public static final bvr T = a("stripped_dark_oak_log", a(cxe.B, cxe.B));
	public static final bvr U = a("stripped_oak_log", a(cxe.o, cxe.o));
	public static final bvr V = a("oak_wood", new cao(cfi.c.a(cxd.x, cxe.o).d(2.0F).a(cbh.a)));
	public static final bvr W = a("spruce_wood", new cao(cfi.c.a(cxd.x, cxe.J).d(2.0F).a(cbh.a)));
	public static final bvr X = a("birch_wood", new cao(cfi.c.a(cxd.x, cxe.d).d(2.0F).a(cbh.a)));
	public static final bvr Y = a("jungle_wood", new cao(cfi.c.a(cxd.x, cxe.l).d(2.0F).a(cbh.a)));
	public static final bvr Z = a("acacia_wood", new cao(cfi.c.a(cxd.x, cxe.w).d(2.0F).a(cbh.a)));
	public static final bvr aa = a("dark_oak_wood", new cao(cfi.c.a(cxd.x, cxe.B).d(2.0F).a(cbh.a)));
	public static final bvr ab = a("stripped_oak_wood", new cao(cfi.c.a(cxd.x, cxe.o).d(2.0F).a(cbh.a)));
	public static final bvr ac = a("stripped_spruce_wood", new cao(cfi.c.a(cxd.x, cxe.J).d(2.0F).a(cbh.a)));
	public static final bvr ad = a("stripped_birch_wood", new cao(cfi.c.a(cxd.x, cxe.d).d(2.0F).a(cbh.a)));
	public static final bvr ae = a("stripped_jungle_wood", new cao(cfi.c.a(cxd.x, cxe.l).d(2.0F).a(cbh.a)));
	public static final bvr af = a("stripped_acacia_wood", new cao(cfi.c.a(cxd.x, cxe.q).d(2.0F).a(cbh.a)));
	public static final bvr ag = a("stripped_dark_oak_wood", new cao(cfi.c.a(cxd.x, cxe.B).d(2.0F).a(cbh.a)));
	public static final bvr ah = a("oak_leaves", b());
	public static final bvr ai = a("spruce_leaves", b());
	public static final bvr aj = a("birch_leaves", b());
	public static final bvr ak = a("jungle_leaves", b());
	public static final bvr al = a("acacia_leaves", b());
	public static final bvr am = a("dark_oak_leaves", b());
	public static final bvr an = a("sponge", new cbj(cfi.c.a(cxd.v).d(0.6F).a(cbh.c)));
	public static final bvr ao = a("wet_sponge", new ccv(cfi.c.a(cxd.v).d(0.6F).a(cbh.c)));
	public static final bvr ap = a("glass", new byc(cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b().a(bvs::a).a(bvs::b).b(bvs::b).c(bvs::b)));
	public static final bvr aq = a("lapis_ore", new bzu(cfi.c.a(cxd.H).h().a(3.0F, 3.0F)));
	public static final bvr ar = a("lapis_block", new bvr(cfi.c.a(cxd.I, cxe.H).h().a(3.0F, 3.0F)));
	public static final bvr as = a("dispenser", new bxd(cfi.c.a(cxd.H).h().d(3.5F)));
	public static final bvr at = a("sandstone", new bvr(cfi.c.a(cxd.H, cxe.d).h().d(0.8F)));
	public static final bvr au = a("chiseled_sandstone", new bvr(cfi.c.a(cxd.H, cxe.d).h().d(0.8F)));
	public static final bvr av = a("cut_sandstone", new bvr(cfi.c.a(cxd.H, cxe.d).h().d(0.8F)));
	public static final bvr aw = a("note_block", new bzr(cfi.c.a(cxd.x).a(cbh.a).d(0.8F)));
	public static final bvr ax = a("white_bed", a(bje.WHITE));
	public static final bvr ay = a("orange_bed", a(bje.ORANGE));
	public static final bvr az = a("magenta_bed", a(bje.MAGENTA));
	public static final bvr aA = a("light_blue_bed", a(bje.LIGHT_BLUE));
	public static final bvr aB = a("yellow_bed", a(bje.YELLOW));
	public static final bvr aC = a("lime_bed", a(bje.LIME));
	public static final bvr aD = a("pink_bed", a(bje.PINK));
	public static final bvr aE = a("gray_bed", a(bje.GRAY));
	public static final bvr aF = a("light_gray_bed", a(bje.LIGHT_GRAY));
	public static final bvr aG = a("cyan_bed", a(bje.CYAN));
	public static final bvr aH = a("purple_bed", a(bje.PURPLE));
	public static final bvr aI = a("blue_bed", a(bje.BLUE));
	public static final bvr aJ = a("brown_bed", a(bje.BROWN));
	public static final bvr aK = a("green_bed", a(bje.GREEN));
	public static final bvr aL = a("red_bed", a(bje.RED));
	public static final bvr aM = a("black_bed", a(bje.BLACK));
	public static final bvr aN = a("powered_rail", new caa(cfi.c.a(cxd.n).a().d(0.7F).a(cbh.f)));
	public static final bvr aO = a("detector_rail", new bxa(cfi.c.a(cxd.n).a().d(0.7F).a(cbh.f)));
	public static final bvr aP = a("sticky_piston", a(true));
	public static final bvr aQ = a("cobweb", new ccr(cfi.c.a(cxd.o).a().h().d(4.0F)));
	public static final bvr aR = a("grass", new cby(cfi.c.a(cxd.g).a().c().a(cbh.c)));
	public static final bvr aS = a("fern", new cby(cfi.c.a(cxd.g).a().c().a(cbh.c)));
	public static final bvr aT = a("dead_bush", new bwz(cfi.c.a(cxd.g, cxe.o).a().c().a(cbh.c)));
	public static final bvr aU = a("seagrass", new cau(cfi.c.a(cxd.h).a().c().a(cbh.o)));
	public static final bvr aV = a("tall_seagrass", new cbz(cfi.c.a(cxd.h).a().c().a(cbh.o)));
	public static final bvr aW = a("piston", a(false));
	public static final bvr aX = a("piston_head", new cfd(cfi.c.a(cxd.M).d(1.5F).f()));
	public static final bvr aY = a("white_wool", new bvr(cfi.c.a(cxd.B, cxe.j).d(0.8F).a(cbh.h)));
	public static final bvr aZ = a("orange_wool", new bvr(cfi.c.a(cxd.B, cxe.q).d(0.8F).a(cbh.h)));
	public static final bvr ba = a("magenta_wool", new bvr(cfi.c.a(cxd.B, cxe.r).d(0.8F).a(cbh.h)));
	public static final bvr bb = a("light_blue_wool", new bvr(cfi.c.a(cxd.B, cxe.s).d(0.8F).a(cbh.h)));
	public static final bvr bc = a("yellow_wool", new bvr(cfi.c.a(cxd.B, cxe.t).d(0.8F).a(cbh.h)));
	public static final bvr bd = a("lime_wool", new bvr(cfi.c.a(cxd.B, cxe.u).d(0.8F).a(cbh.h)));
	public static final bvr be = a("pink_wool", new bvr(cfi.c.a(cxd.B, cxe.v).d(0.8F).a(cbh.h)));
	public static final bvr bf = a("gray_wool", new bvr(cfi.c.a(cxd.B, cxe.w).d(0.8F).a(cbh.h)));
	public static final bvr bg = a("light_gray_wool", new bvr(cfi.c.a(cxd.B, cxe.x).d(0.8F).a(cbh.h)));
	public static final bvr bh = a("cyan_wool", new bvr(cfi.c.a(cxd.B, cxe.y).d(0.8F).a(cbh.h)));
	public static final bvr bi = a("purple_wool", new bvr(cfi.c.a(cxd.B, cxe.z).d(0.8F).a(cbh.h)));
	public static final bvr bj = a("blue_wool", new bvr(cfi.c.a(cxd.B, cxe.A).d(0.8F).a(cbh.h)));
	public static final bvr bk = a("brown_wool", new bvr(cfi.c.a(cxd.B, cxe.B).d(0.8F).a(cbh.h)));
	public static final bvr bl = a("green_wool", new bvr(cfi.c.a(cxd.B, cxe.C).d(0.8F).a(cbh.h)));
	public static final bvr bm = a("red_wool", new bvr(cfi.c.a(cxd.B, cxe.D).d(0.8F).a(cbh.h)));
	public static final bvr bn = a("black_wool", new bvr(cfi.c.a(cxd.B, cxe.E).d(0.8F).a(cbh.h)));
	public static final bvr bo = a("moving_piston", new cfb(cfi.c.a(cxd.M).d(-1.0F).e().f().b().a(bvs::b).b(bvs::b).c(bvs::b)));
	public static final bvr bp = a("dandelion", new bxx(aoi.w, 7, cfi.c.a(cxd.e).a().c().a(cbh.c)));
	public static final bvr bq = a("poppy", new bxx(aoi.p, 5, cfi.c.a(cxd.e).a().c().a(cbh.c)));
	public static final bvr br = a("blue_orchid", new bxx(aoi.w, 7, cfi.c.a(cxd.e).a().c().a(cbh.c)));
	public static final bvr bs = a("allium", new bxx(aoi.l, 4, cfi.c.a(cxd.e).a().c().a(cbh.c)));
	public static final bvr bt = a("azure_bluet", new bxx(aoi.o, 8, cfi.c.a(cxd.e).a().c().a(cbh.c)));
	public static final bvr bu = a("red_tulip", new bxx(aoi.r, 9, cfi.c.a(cxd.e).a().c().a(cbh.c)));
	public static final bvr bv = a("orange_tulip", new bxx(aoi.r, 9, cfi.c.a(cxd.e).a().c().a(cbh.c)));
	public static final bvr bw = a("white_tulip", new bxx(aoi.r, 9, cfi.c.a(cxd.e).a().c().a(cbh.c)));
	public static final bvr bx = a("pink_tulip", new bxx(aoi.r, 9, cfi.c.a(cxd.e).a().c().a(cbh.c)));
	public static final bvr by = a("oxeye_daisy", new bxx(aoi.j, 8, cfi.c.a(cxd.e).a().c().a(cbh.c)));
	public static final bvr bz = a("cornflower", new bxx(aoi.h, 6, cfi.c.a(cxd.e).a().c().a(cbh.c)));
	public static final bvr bA = a("wither_rose", new ccw(aoi.t, cfi.c.a(cxd.e).a().c().a(cbh.c)));
	public static final bvr bB = a("lily_of_the_valley", new bxx(aoi.s, 12, cfi.c.a(cxd.e).a().c().a(cbh.c)));
	public static final bvr bC = a("brown_mushroom", new bzk(cfi.c.a(cxd.e, cxe.B).a().d().c().a(cbh.c).a(cfj -> 1).d(bvs::a)));
	public static final bvr bD = a("red_mushroom", new bzk(cfi.c.a(cxd.e, cxe.D).a().d().c().a(cbh.c).d(bvs::a)));
	public static final bvr bE = a("gold_block", new bvr(cfi.c.a(cxd.I, cxe.F).h().a(3.0F, 6.0F).a(cbh.f)));
	public static final bvr bF = a("iron_block", new bvr(cfi.c.a(cxd.I, cxe.h).h().a(5.0F, 6.0F).a(cbh.f)));
	public static final bvr bG = a("bricks", new bvr(cfi.c.a(cxd.H, cxe.D).h().a(2.0F, 6.0F)));
	public static final bvr bH = a("tnt", new ccb(cfi.c.a(cxd.C).c().a(cbh.c)));
	public static final bvr bI = a("bookshelf", new bvr(cfi.c.a(cxd.x).d(1.5F).a(cbh.a)));
	public static final bvr bJ = a("mossy_cobblestone", new bvr(cfi.c.a(cxd.H).h().a(2.0F, 6.0F)));
	public static final bvr bK = a("obsidian", new bvr(cfi.c.a(cxd.H, cxe.E).h().a(50.0F, 1200.0F)));
	public static final bvr bL = a("torch", new ccc(cfi.c.a(cxd.n).a().c().a(cfj -> 14).a(cbh.a), hh.A));
	public static final bvr bM = a("wall_torch", new ccp(cfi.c.a(cxd.n).a().c().a(cfj -> 14).a(cbh.a).a(bL), hh.A));
	public static final bvr bN = a("fire", new bxv(cfi.c.a(cxd.m, cxe.f).a().c().a(cfj -> 15).a(cbh.h)));
	public static final bvr bO = a("soul_fire", new cbf(cfi.c.a(cxd.m, cxe.s).a().c().a(cfj -> 10).a(cbh.h)));
	public static final bvr bP = a("spawner", new cbi(cfi.c.a(cxd.H).h().d(5.0F).a(cbh.f).b()));
	public static final bvr bQ = a("oak_stairs", new cbn(n.n(), cfi.c.a((cfi)n)));
	public static final bvr bR = a("chest", new bwh(cfi.c.a(cxd.x).d(2.5F).a(cbh.a), () -> cdm.b));
	public static final bvr bS = a("redstone_wire", new cag(cfi.c.a(cxd.n).a().c()));
	public static final bvr bT = a("diamond_ore", new bzu(cfi.c.a(cxd.H).h().a(3.0F, 3.0F)));
	public static final bvr bU = a("diamond_block", new bvr(cfi.c.a(cxd.I, cxe.G).h().a(5.0F, 6.0F).a(cbh.f)));
	public static final bvr bV = a("crafting_table", new bwu(cfi.c.a(cxd.x).d(2.5F).a(cbh.a)));
	public static final bvr bW = a("wheat", new bwv(cfi.c.a(cxd.e).a().d().c().a(cbh.u)));
	public static final bvr bX = a("farmland", new bxs(cfi.c.a(cxd.r).d().d(0.6F).a(cbh.b).c(bvs::a)));
	public static final bvr bY = a("furnace", new byb(cfi.c.a(cxd.H).h().d(3.5F).a(a(13))));
	public static final bvr bZ = a("oak_sign", new cbo(cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a), cgs.a));
	public static final bvr ca = a("spruce_sign", new cbo(cfi.c.a(cxd.x, K.s()).a().d(1.0F).a(cbh.a), cgs.b));
	public static final bvr cb = a("birch_sign", new cbo(cfi.c.a(cxd.x, cxe.d).a().d(1.0F).a(cbh.a), cgs.c));
	public static final bvr cc = a("acacia_sign", new cbo(cfi.c.a(cxd.x, cxe.q).a().d(1.0F).a(cbh.a), cgs.d));
	public static final bvr cd = a("jungle_sign", new cbo(cfi.c.a(cxd.x, M.s()).a().d(1.0F).a(cbh.a), cgs.e));
	public static final bvr ce = a("dark_oak_sign", new cbo(cfi.c.a(cxd.x, O.s()).a().d(1.0F).a(cbh.a), cgs.f));
	public static final bvr cf = a("oak_door", new bxe(cfi.c.a(cxd.x, n.s()).d(3.0F).a(cbh.a).b()));
	public static final bvr cg = a("ladder", new byy(cfi.c.a(cxd.n).d(0.4F).a(cbh.k).b()));
	public static final bvr ch = a("rail", new cad(cfi.c.a(cxd.n).a().d(0.7F).a(cbh.f)));
	public static final bvr ci = a("cobblestone_stairs", new cbn(m.n(), cfi.c.a((cfi)m)));
	public static final bvr cj = a("oak_wall_sign", new ccn(cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(bZ), cgs.a));
	public static final bvr ck = a("spruce_wall_sign", new ccn(cfi.c.a(cxd.x, K.s()).a().d(1.0F).a(cbh.a).a(ca), cgs.b));
	public static final bvr cl = a("birch_wall_sign", new ccn(cfi.c.a(cxd.x, cxe.d).a().d(1.0F).a(cbh.a).a(cb), cgs.c));
	public static final bvr cm = a("acacia_wall_sign", new ccn(cfi.c.a(cxd.x, cxe.q).a().d(1.0F).a(cbh.a).a(cc), cgs.d));
	public static final bvr cn = a("jungle_wall_sign", new ccn(cfi.c.a(cxd.x, M.s()).a().d(1.0F).a(cbh.a).a(cd), cgs.e));
	public static final bvr co = a("dark_oak_wall_sign", new ccn(cfi.c.a(cxd.x, O.s()).a().d(1.0F).a(cbh.a).a(ce), cgs.f));
	public static final bvr cp = a("lever", new bzd(cfi.c.a(cxd.n).a().d(0.5F).a(cbh.a)));
	public static final bvr cq = a("stone_pressure_plate", new cab(cab.a.MOBS, cfi.c.a(cxd.H).h().a().d(0.5F)));
	public static final bvr cr = a("iron_door", new bxe(cfi.c.a(cxd.I, cxe.h).h().d(5.0F).a(cbh.f).b()));
	public static final bvr cs = a("oak_pressure_plate", new cab(cab.a.EVERYTHING, cfi.c.a(cxd.x, n.s()).a().d(0.5F).a(cbh.a)));
	public static final bvr ct = a("spruce_pressure_plate", new cab(cab.a.EVERYTHING, cfi.c.a(cxd.x, o.s()).a().d(0.5F).a(cbh.a)));
	public static final bvr cu = a("birch_pressure_plate", new cab(cab.a.EVERYTHING, cfi.c.a(cxd.x, p.s()).a().d(0.5F).a(cbh.a)));
	public static final bvr cv = a("jungle_pressure_plate", new cab(cab.a.EVERYTHING, cfi.c.a(cxd.x, q.s()).a().d(0.5F).a(cbh.a)));
	public static final bvr cw = a("acacia_pressure_plate", new cab(cab.a.EVERYTHING, cfi.c.a(cxd.x, r.s()).a().d(0.5F).a(cbh.a)));
	public static final bvr cx = a("dark_oak_pressure_plate", new cab(cab.a.EVERYTHING, cfi.c.a(cxd.x, s.s()).a().d(0.5F).a(cbh.a)));
	public static final bvr cy = a("redstone_ore", new caf(cfi.c.a(cxd.H).h().d().a(a(9)).a(3.0F, 3.0F)));
	public static final bvr cz = a("redstone_torch", new cai(cfi.c.a(cxd.n).a().c().a(a(7)).a(cbh.a)));
	public static final bvr cA = a("redstone_wall_torch", new caj(cfi.c.a(cxd.n).a().c().a(a(7)).a(cbh.a).a(cz)));
	public static final bvr cB = a("stone_button", new cbr(cfi.c.a(cxd.n).a().d(0.5F)));
	public static final bvr cC = a("snow", new cbd(cfi.c.a(cxd.l).d().d(0.1F).h().a(cbh.j)));
	public static final bvr cD = a("ice", new byr(cfi.c.a(cxd.F).a(0.98F).d().d(0.5F).a(cbh.g).b().a((cfi.d<aoq<?>>)((cfj, bpg, fu, aoq) -> aoq == aoq.ak))));
	public static final bvr cE = a("snow_block", new bvr(cfi.c.a(cxd.J).h().d(0.2F).a(cbh.j)));
	public static final bvr cF = a("cactus", new bvz(cfi.c.a(cxd.G).d().d(0.4F).a(cbh.h)));
	public static final bvr cG = a("clay", new bvr(cfi.c.a(cxd.q).d(0.6F).a(cbh.b)));
	public static final bvr cH = a("sugar_cane", new cbv(cfi.c.a(cxd.e).a().d().c().a(cbh.c)));
	public static final bvr cI = a("jukebox", new byv(cfi.c.a(cxd.x, cxe.l).a(2.0F, 6.0F)));
	public static final bvr cJ = a("oak_fence", new bxt(cfi.c.a(cxd.x, n.s()).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr cK = a("pumpkin", new cac(cfi.c.a(cxd.O, cxe.q).d(1.0F).a(cbh.a)));
	public static final bvr cL = a("netherrack", new bzq(cfi.c.a(cxd.H, cxe.K).h().d(0.4F).a(cbh.K)));
	public static final bvr cM = a("soul_sand", new cbg(cfi.c.a(cxd.u, cxe.B).d(0.5F).b(0.4F).a(cbh.G).a(bvs::b).a(bvs::a).c(bvs::a)));
	public static final bvr cN = a("soul_soil", new bvr(cfi.c.a(cxd.r, cxe.B).d(0.5F).a(cbh.H)));
	public static final bvr cO = a("basalt", new cao(cfi.c.a(cxd.H, cxe.E).h().a(1.25F, 4.2F).a(cbh.I)));
	public static final bvr cP = a("polished_basalt", new cao(cfi.c.a(cxd.H, cxe.E).h().a(1.25F, 4.2F).a(cbh.I)));
	public static final bvr cQ = a("soul_torch", new ccc(cfi.c.a(cxd.n).a().c().a(cfj -> 10).a(cbh.a), hh.B));
	public static final bvr cR = a("soul_wall_torch", new ccp(cfi.c.a(cxd.n).a().c().a(cfj -> 10).a(cbh.a).a(cQ), hh.B));
	public static final bvr cS = a("glowstone", new bvr(cfi.c.a(cxd.E, cxe.d).d(0.3F).a(cbh.g).a(cfj -> 15)));
	public static final bvr cT = a("nether_portal", new bzm(cfi.c.a(cxd.c).a().d().d(-1.0F).a(cbh.g).a(cfj -> 11)));
	public static final bvr cU = a("carved_pumpkin", new bwe(cfi.c.a(cxd.O, cxe.q).d(1.0F).a(cbh.a).a(bvs::b)));
	public static final bvr cV = a("jack_o_lantern", new bwe(cfi.c.a(cxd.O, cxe.q).d(1.0F).a(cbh.a).a(cfj -> 15).a(bvs::b)));
	public static final bvr cW = a("cake", new bwa(cfi.c.a(cxd.Q).d(0.5F).a(cbh.h)));
	public static final bvr cX = a("repeater", new cal(cfi.c.a(cxd.n).c().a(cbh.a)));
	public static final bvr cY = a("white_stained_glass", b(bje.WHITE));
	public static final bvr cZ = a("orange_stained_glass", b(bje.ORANGE));
	public static final bvr da = a("magenta_stained_glass", b(bje.MAGENTA));
	public static final bvr db = a("light_blue_stained_glass", b(bje.LIGHT_BLUE));
	public static final bvr dc = a("yellow_stained_glass", b(bje.YELLOW));
	public static final bvr dd = a("lime_stained_glass", b(bje.LIME));
	public static final bvr de = a("pink_stained_glass", b(bje.PINK));
	public static final bvr df = a("gray_stained_glass", b(bje.GRAY));
	public static final bvr dg = a("light_gray_stained_glass", b(bje.LIGHT_GRAY));
	public static final bvr dh = a("cyan_stained_glass", b(bje.CYAN));
	public static final bvr di = a("purple_stained_glass", b(bje.PURPLE));
	public static final bvr dj = a("blue_stained_glass", b(bje.BLUE));
	public static final bvr dk = a("brown_stained_glass", b(bje.BROWN));
	public static final bvr dl = a("green_stained_glass", b(bje.GREEN));
	public static final bvr dm = a("red_stained_glass", b(bje.RED));
	public static final bvr dn = a("black_stained_glass", b(bje.BLACK));
	public static final bvr do = a("oak_trapdoor", new ccd(cfi.c.a(cxd.x, cxe.o).d(3.0F).a(cbh.a).b().a(bvs::a)));
	public static final bvr dp = a("spruce_trapdoor", new ccd(cfi.c.a(cxd.x, cxe.J).d(3.0F).a(cbh.a).b().a(bvs::a)));
	public static final bvr dq = a("birch_trapdoor", new ccd(cfi.c.a(cxd.x, cxe.d).d(3.0F).a(cbh.a).b().a(bvs::a)));
	public static final bvr dr = a("jungle_trapdoor", new ccd(cfi.c.a(cxd.x, cxe.l).d(3.0F).a(cbh.a).b().a(bvs::a)));
	public static final bvr ds = a("acacia_trapdoor", new ccd(cfi.c.a(cxd.x, cxe.q).d(3.0F).a(cbh.a).b().a(bvs::a)));
	public static final bvr dt = a("dark_oak_trapdoor", new ccd(cfi.c.a(cxd.x, cxe.B).d(3.0F).a(cbh.a).b().a(bvs::a)));
	public static final bvr du = a("stone_bricks", new bvr(cfi.c.a(cxd.H).h().a(1.5F, 6.0F)));
	public static final bvr dv = a("mossy_stone_bricks", new bvr(cfi.c.a(cxd.H).h().a(1.5F, 6.0F)));
	public static final bvr dw = a("cracked_stone_bricks", new bvr(cfi.c.a(cxd.H).h().a(1.5F, 6.0F)));
	public static final bvr dx = a("chiseled_stone_bricks", new bvr(cfi.c.a(cxd.H).h().a(1.5F, 6.0F)));
	public static final bvr dy = a("infested_stone", new bys(b, cfi.c.a(cxd.q).a(0.0F, 0.75F)));
	public static final bvr dz = a("infested_cobblestone", new bys(m, cfi.c.a(cxd.q).a(0.0F, 0.75F)));
	public static final bvr dA = a("infested_stone_bricks", new bys(du, cfi.c.a(cxd.q).a(0.0F, 0.75F)));
	public static final bvr dB = a("infested_mossy_stone_bricks", new bys(dv, cfi.c.a(cxd.q).a(0.0F, 0.75F)));
	public static final bvr dC = a("infested_cracked_stone_bricks", new bys(dw, cfi.c.a(cxd.q).a(0.0F, 0.75F)));
	public static final bvr dD = a("infested_chiseled_stone_bricks", new bys(dx, cfi.c.a(cxd.q).a(0.0F, 0.75F)));
	public static final bvr dE = a("brown_mushroom_block", new byq(cfi.c.a(cxd.x, cxe.l).d(0.2F).a(cbh.a)));
	public static final bvr dF = a("red_mushroom_block", new byq(cfi.c.a(cxd.x, cxe.D).d(0.2F).a(cbh.a)));
	public static final bvr dG = a("mushroom_stem", new byq(cfi.c.a(cxd.x, cxe.e).d(0.2F).a(cbh.a)));
	public static final bvr dH = a("iron_bars", new byt(cfi.c.a(cxd.I, cxe.b).h().a(5.0F, 6.0F).a(cbh.f).b()));
	public static final bvr dI = a("chain", new bwg(cfi.c.a(cxd.I, cxe.b).h().a(5.0F, 6.0F).a(cbh.S).b()));
	public static final bvr dJ = a("glass_pane", new byt(cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr dK = a("melon", new bzi(cfi.c.a(cxd.O, cxe.u).d(1.0F).a(cbh.a)));
	public static final bvr dL = a("attached_pumpkin_stem", new buw((cbq)cK, cfi.c.a(cxd.e).a().c().a(cbh.a)));
	public static final bvr dM = a("attached_melon_stem", new buw((cbq)dK, cfi.c.a(cxd.e).a().c().a(cbh.a)));
	public static final bvr dN = a("pumpkin_stem", new cbp((cbq)cK, cfi.c.a(cxd.e).a().d().c().a(cbh.v)));
	public static final bvr dO = a("melon_stem", new cbp((cbq)dK, cfi.c.a(cxd.e).a().d().c().a(cbh.v)));
	public static final bvr dP = a("vine", new cck(cfi.c.a(cxd.g).a().d().d(0.2F).a(cbh.w)));
	public static final bvr dQ = a("oak_fence_gate", new bxu(cfi.c.a(cxd.x, n.s()).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr dR = a("brick_stairs", new cbn(bG.n(), cfi.c.a((cfi)bG)));
	public static final bvr dS = a("stone_brick_stairs", new cbn(du.n(), cfi.c.a((cfi)du)));
	public static final bvr dT = a("mycelium", new bzl(cfi.c.a(cxd.s, cxe.z).d().d(0.6F).a(cbh.c)));
	public static final bvr dU = a("lily_pad", new ccq(cfi.c.a(cxd.e).c().a(cbh.d).b()));
	public static final bvr dV = a("nether_bricks", new bvr(cfi.c.a(cxd.H, cxe.K).h().a(2.0F, 6.0F).a(cbh.L)));
	public static final bvr dW = a("nether_brick_fence", new bxt(cfi.c.a(cxd.H, cxe.K).h().a(2.0F, 6.0F).a(cbh.L)));
	public static final bvr dX = a("nether_brick_stairs", new cbn(dV.n(), cfi.c.a((cfi)dV)));
	public static final bvr dY = a("nether_wart", new bzp(cfi.c.a(cxd.e, cxe.D).a().d().a(cbh.x)));
	public static final bvr dZ = a("enchanting_table", new bxj(cfi.c.a(cxd.H, cxe.D).h().a(5.0F, 1200.0F)));
	public static final bvr ea = a("brewing_stand", new bvu(cfi.c.a(cxd.I).h().d(0.5F).a(cfj -> 1).b()));
	public static final bvr eb = a("cauldron", new bwf(cfi.c.a(cxd.I, cxe.m).h().d(2.0F).b()));
	public static final bvr ec = a("end_portal", new bxl(cfi.c.a(cxd.c, cxe.E).a().a(cfj -> 15).a(-1.0F, 3600000.0F).f()));
	public static final bvr ed = a("end_portal_frame", new bxm(cfi.c.a(cxd.H, cxe.C).a(cbh.g).a(cfj -> 1).a(-1.0F, 3600000.0F).f()));
	public static final bvr ee = a("end_stone", new bvr(cfi.c.a(cxd.H, cxe.d).h().a(3.0F, 9.0F)));
	public static final bvr ef = a("dragon_egg", new bxh(cfi.c.a(cxd.P, cxe.E).a(3.0F, 9.0F).a(cfj -> 1).b()));
	public static final bvr eg = a("redstone_lamp", new cah(cfi.c.a(cxd.p).a(a(15)).d(0.3F).a(cbh.g).a(bvs::b)));
	public static final bvr eh = a("cocoa", new bwk(cfi.c.a(cxd.e).d().a(0.2F, 3.0F).a(cbh.a).b()));
	public static final bvr ei = a("sandstone_stairs", new cbn(at.n(), cfi.c.a((cfi)at)));
	public static final bvr ej = a("emerald_ore", new bzu(cfi.c.a(cxd.H).h().a(3.0F, 3.0F)));
	public static final bvr ek = a("ender_chest", new bxo(cfi.c.a(cxd.H).h().a(22.5F, 600.0F).a(cfj -> 7)));
	public static final bvr el = a("tripwire_hook", new ccg(cfi.c.a(cxd.n).a()));
	public static final bvr em = a("tripwire", new ccf((ccg)el, cfi.c.a(cxd.n).a()));
	public static final bvr en = a("emerald_block", new bvr(cfi.c.a(cxd.I, cxe.I).h().a(5.0F, 6.0F).a(cbh.f)));
	public static final bvr eo = a("spruce_stairs", new cbn(o.n(), cfi.c.a((cfi)o)));
	public static final bvr ep = a("birch_stairs", new cbn(p.n(), cfi.c.a((cfi)p)));
	public static final bvr eq = a("jungle_stairs", new cbn(q.n(), cfi.c.a((cfi)q)));
	public static final bvr er = a("command_block", new bwl(cfi.c.a(cxd.I, cxe.B).h().a(-1.0F, 3600000.0F).f()));
	public static final bvr es = a("beacon", new bvl(cfi.c.a(cxd.E, cxe.G).d(3.0F).a(cfj -> 15).b().a(bvs::b)));
	public static final bvr et = a("cobblestone_wall", new ccm(cfi.c.a((cfi)m)));
	public static final bvr eu = a("mossy_cobblestone_wall", new ccm(cfi.c.a((cfi)m)));
	public static final bvr ev = a("flower_pot", new bxy(a, cfi.c.a(cxd.n).c().b()));
	public static final bvr ew = a("potted_oak_sapling", new bxy(t, cfi.c.a(cxd.n).c().b()));
	public static final bvr ex = a("potted_spruce_sapling", new bxy(u, cfi.c.a(cxd.n).c().b()));
	public static final bvr ey = a("potted_birch_sapling", new bxy(v, cfi.c.a(cxd.n).c().b()));
	public static final bvr ez = a("potted_jungle_sapling", new bxy(w, cfi.c.a(cxd.n).c().b()));
	public static final bvr eA = a("potted_acacia_sapling", new bxy(x, cfi.c.a(cxd.n).c().b()));
	public static final bvr eB = a("potted_dark_oak_sapling", new bxy(y, cfi.c.a(cxd.n).c().b()));
	public static final bvr eC = a("potted_fern", new bxy(aS, cfi.c.a(cxd.n).c().b()));
	public static final bvr eD = a("potted_dandelion", new bxy(bp, cfi.c.a(cxd.n).c().b()));
	public static final bvr eE = a("potted_poppy", new bxy(bq, cfi.c.a(cxd.n).c().b()));
	public static final bvr eF = a("potted_blue_orchid", new bxy(br, cfi.c.a(cxd.n).c().b()));
	public static final bvr eG = a("potted_allium", new bxy(bs, cfi.c.a(cxd.n).c().b()));
	public static final bvr eH = a("potted_azure_bluet", new bxy(bt, cfi.c.a(cxd.n).c().b()));
	public static final bvr eI = a("potted_red_tulip", new bxy(bu, cfi.c.a(cxd.n).c().b()));
	public static final bvr eJ = a("potted_orange_tulip", new bxy(bv, cfi.c.a(cxd.n).c().b()));
	public static final bvr eK = a("potted_white_tulip", new bxy(bw, cfi.c.a(cxd.n).c().b()));
	public static final bvr eL = a("potted_pink_tulip", new bxy(bx, cfi.c.a(cxd.n).c().b()));
	public static final bvr eM = a("potted_oxeye_daisy", new bxy(by, cfi.c.a(cxd.n).c().b()));
	public static final bvr eN = a("potted_cornflower", new bxy(bz, cfi.c.a(cxd.n).c().b()));
	public static final bvr eO = a("potted_lily_of_the_valley", new bxy(bB, cfi.c.a(cxd.n).c().b()));
	public static final bvr eP = a("potted_wither_rose", new bxy(bA, cfi.c.a(cxd.n).c().b()));
	public static final bvr eQ = a("potted_red_mushroom", new bxy(bD, cfi.c.a(cxd.n).c().b()));
	public static final bvr eR = a("potted_brown_mushroom", new bxy(bC, cfi.c.a(cxd.n).c().b()));
	public static final bvr eS = a("potted_dead_bush", new bxy(aT, cfi.c.a(cxd.n).c().b()));
	public static final bvr eT = a("potted_cactus", new bxy(cF, cfi.c.a(cxd.n).c().b()));
	public static final bvr eU = a("carrots", new bwc(cfi.c.a(cxd.e).a().d().c().a(cbh.u)));
	public static final bvr eV = a("potatoes", new bzy(cfi.c.a(cxd.e).a().d().c().a(cbh.u)));
	public static final bvr eW = a("oak_button", new ccz(cfi.c.a(cxd.n).a().d(0.5F).a(cbh.a)));
	public static final bvr eX = a("spruce_button", new ccz(cfi.c.a(cxd.n).a().d(0.5F).a(cbh.a)));
	public static final bvr eY = a("birch_button", new ccz(cfi.c.a(cxd.n).a().d(0.5F).a(cbh.a)));
	public static final bvr eZ = a("jungle_button", new ccz(cfi.c.a(cxd.n).a().d(0.5F).a(cbh.a)));
	public static final bvr fa = a("acacia_button", new ccz(cfi.c.a(cxd.n).a().d(0.5F).a(cbh.a)));
	public static final bvr fb = a("dark_oak_button", new ccz(cfi.c.a(cxd.n).a().d(0.5F).a(cbh.a)));
	public static final bvr fc = a("skeleton_skull", new cay(cay.b.SKELETON, cfi.c.a(cxd.n).d(1.0F)));
	public static final bvr fd = a("skeleton_wall_skull", new cco(cay.b.SKELETON, cfi.c.a(cxd.n).d(1.0F).a(fc)));
	public static final bvr fe = a("wither_skeleton_skull", new ccx(cfi.c.a(cxd.n).d(1.0F)));
	public static final bvr ff = a("wither_skeleton_wall_skull", new ccy(cfi.c.a(cxd.n).d(1.0F).a(fe)));
	public static final bvr fg = a("zombie_head", new cay(cay.b.ZOMBIE, cfi.c.a(cxd.n).d(1.0F)));
	public static final bvr fh = a("zombie_wall_head", new cco(cay.b.ZOMBIE, cfi.c.a(cxd.n).d(1.0F).a(fg)));
	public static final bvr fi = a("player_head", new bzw(cfi.c.a(cxd.n).d(1.0F)));
	public static final bvr fj = a("player_wall_head", new bzx(cfi.c.a(cxd.n).d(1.0F).a(fi)));
	public static final bvr fk = a("creeper_head", new cay(cay.b.CREEPER, cfi.c.a(cxd.n).d(1.0F)));
	public static final bvr fl = a("creeper_wall_head", new cco(cay.b.CREEPER, cfi.c.a(cxd.n).d(1.0F).a(fk)));
	public static final bvr fm = a("dragon_head", new cay(cay.b.DRAGON, cfi.c.a(cxd.n).d(1.0F)));
	public static final bvr fn = a("dragon_wall_head", new cco(cay.b.DRAGON, cfi.c.a(cxd.n).d(1.0F).a(fm)));
	public static final bvr fo = a("anvil", new buv(cfi.c.a(cxd.K, cxe.h).h().a(5.0F, 1200.0F).a(cbh.l)));
	public static final bvr fp = a("chipped_anvil", new buv(cfi.c.a(cxd.K, cxe.h).h().a(5.0F, 1200.0F).a(cbh.l)));
	public static final bvr fq = a("damaged_anvil", new buv(cfi.c.a(cxd.K, cxe.h).h().a(5.0F, 1200.0F).a(cbh.l)));
	public static final bvr fr = a("trapped_chest", new cce(cfi.c.a(cxd.x).d(2.5F).a(cbh.a)));
	public static final bvr fs = a("light_weighted_pressure_plate", new ccu(15, cfi.c.a(cxd.I, cxe.F).h().a().d(0.5F).a(cbh.a)));
	public static final bvr ft = a("heavy_weighted_pressure_plate", new ccu(150, cfi.c.a(cxd.I).h().a().d(0.5F).a(cbh.a)));
	public static final bvr fu = a("comparator", new bwm(cfi.c.a(cxd.n).c().a(cbh.a)));
	public static final bvr fv = a("daylight_detector", new bwy(cfi.c.a(cxd.x).d(0.2F).a(cbh.a)));
	public static final bvr fw = a("redstone_block", new bzz(cfi.c.a(cxd.I, cxe.f).h().a(5.0F, 6.0F).a(cbh.f).a(bvs::b)));
	public static final bvr fx = a("nether_quartz_ore", new bzu(cfi.c.a(cxd.H, cxe.K).h().a(3.0F, 3.0F).a(cbh.N)));
	public static final bvr fy = a("hopper", new byo(cfi.c.a(cxd.I, cxe.m).h().a(3.0F, 4.8F).a(cbh.f).b()));
	public static final bvr fz = a("quartz_block", new bvr(cfi.c.a(cxd.H, cxe.p).h().d(0.8F)));
	public static final bvr fA = a("chiseled_quartz_block", new bvr(cfi.c.a(cxd.H, cxe.p).h().d(0.8F)));
	public static final bvr fB = a("quartz_pillar", new cao(cfi.c.a(cxd.H, cxe.p).h().d(0.8F)));
	public static final bvr fC = a("quartz_stairs", new cbn(fz.n(), cfi.c.a((cfi)fz)));
	public static final bvr fD = a("activator_rail", new caa(cfi.c.a(cxd.n).a().d(0.7F).a(cbh.f)));
	public static final bvr fE = a("dropper", new bxi(cfi.c.a(cxd.H).h().d(3.5F)));
	public static final bvr fF = a("white_terracotta", new bvr(cfi.c.a(cxd.H, cxe.L).h().a(1.25F, 4.2F)));
	public static final bvr fG = a("orange_terracotta", new bvr(cfi.c.a(cxd.H, cxe.M).h().a(1.25F, 4.2F)));
	public static final bvr fH = a("magenta_terracotta", new bvr(cfi.c.a(cxd.H, cxe.N).h().a(1.25F, 4.2F)));
	public static final bvr fI = a("light_blue_terracotta", new bvr(cfi.c.a(cxd.H, cxe.O).h().a(1.25F, 4.2F)));
	public static final bvr fJ = a("yellow_terracotta", new bvr(cfi.c.a(cxd.H, cxe.P).h().a(1.25F, 4.2F)));
	public static final bvr fK = a("lime_terracotta", new bvr(cfi.c.a(cxd.H, cxe.Q).h().a(1.25F, 4.2F)));
	public static final bvr fL = a("pink_terracotta", new bvr(cfi.c.a(cxd.H, cxe.R).h().a(1.25F, 4.2F)));
	public static final bvr fM = a("gray_terracotta", new bvr(cfi.c.a(cxd.H, cxe.S).h().a(1.25F, 4.2F)));
	public static final bvr fN = a("light_gray_terracotta", new bvr(cfi.c.a(cxd.H, cxe.T).h().a(1.25F, 4.2F)));
	public static final bvr fO = a("cyan_terracotta", new bvr(cfi.c.a(cxd.H, cxe.U).h().a(1.25F, 4.2F)));
	public static final bvr fP = a("purple_terracotta", new bvr(cfi.c.a(cxd.H, cxe.V).h().a(1.25F, 4.2F)));
	public static final bvr fQ = a("blue_terracotta", new bvr(cfi.c.a(cxd.H, cxe.W).h().a(1.25F, 4.2F)));
	public static final bvr fR = a("brown_terracotta", new bvr(cfi.c.a(cxd.H, cxe.X).h().a(1.25F, 4.2F)));
	public static final bvr fS = a("green_terracotta", new bvr(cfi.c.a(cxd.H, cxe.Y).h().a(1.25F, 4.2F)));
	public static final bvr fT = a("red_terracotta", new bvr(cfi.c.a(cxd.H, cxe.Z).h().a(1.25F, 4.2F)));
	public static final bvr fU = a("black_terracotta", new bvr(cfi.c.a(cxd.H, cxe.aa).h().a(1.25F, 4.2F)));
	public static final bvr fV = a("white_stained_glass_pane", new cbm(bje.WHITE, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr fW = a("orange_stained_glass_pane", new cbm(bje.ORANGE, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr fX = a("magenta_stained_glass_pane", new cbm(bje.MAGENTA, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr fY = a("light_blue_stained_glass_pane", new cbm(bje.LIGHT_BLUE, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr fZ = a("yellow_stained_glass_pane", new cbm(bje.YELLOW, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr ga = a("lime_stained_glass_pane", new cbm(bje.LIME, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr gb = a("pink_stained_glass_pane", new cbm(bje.PINK, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr gc = a("gray_stained_glass_pane", new cbm(bje.GRAY, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr gd = a("light_gray_stained_glass_pane", new cbm(bje.LIGHT_GRAY, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr ge = a("cyan_stained_glass_pane", new cbm(bje.CYAN, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr gf = a("purple_stained_glass_pane", new cbm(bje.PURPLE, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr gg = a("blue_stained_glass_pane", new cbm(bje.BLUE, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr gh = a("brown_stained_glass_pane", new cbm(bje.BROWN, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr gi = a("green_stained_glass_pane", new cbm(bje.GREEN, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr gj = a("red_stained_glass_pane", new cbm(bje.RED, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr gk = a("black_stained_glass_pane", new cbm(bje.BLACK, cfi.c.a(cxd.E).d(0.3F).a(cbh.g).b()));
	public static final bvr gl = a("acacia_stairs", new cbn(r.n(), cfi.c.a((cfi)r)));
	public static final bvr gm = a("dark_oak_stairs", new cbn(s.n(), cfi.c.a((cfi)s)));
	public static final bvr gn = a("slime_block", new cba(cfi.c.a(cxd.q, cxe.c).a(0.8F).a(cbh.m).b()));
	public static final bvr go = a("barrier", new bvb(cfi.c.a(cxd.L).a(-1.0F, 3600000.8F).f().b().a(bvs::a)));
	public static final bvr gp = a("iron_trapdoor", new ccd(cfi.c.a(cxd.I).h().d(5.0F).a(cbh.f).b()));
	public static final bvr gq = a("prismarine", new bvr(cfi.c.a(cxd.H, cxe.y).h().a(1.5F, 6.0F)));
	public static final bvr gr = a("prismarine_bricks", new bvr(cfi.c.a(cxd.H, cxe.G).h().a(1.5F, 6.0F)));
	public static final bvr gs = a("dark_prismarine", new bvr(cfi.c.a(cxd.H, cxe.G).h().a(1.5F, 6.0F)));
	public static final bvr gt = a("prismarine_stairs", new cbn(gq.n(), cfi.c.a((cfi)gq)));
	public static final bvr gu = a("prismarine_brick_stairs", new cbn(gr.n(), cfi.c.a((cfi)gr)));
	public static final bvr gv = a("dark_prismarine_stairs", new cbn(gs.n(), cfi.c.a((cfi)gs)));
	public static final bvr gw = a("prismarine_slab", new caz(cfi.c.a(cxd.H, cxe.y).h().a(1.5F, 6.0F)));
	public static final bvr gx = a("prismarine_brick_slab", new caz(cfi.c.a(cxd.H, cxe.G).h().a(1.5F, 6.0F)));
	public static final bvr gy = a("dark_prismarine_slab", new caz(cfi.c.a(cxd.H, cxe.G).h().a(1.5F, 6.0F)));
	public static final bvr gz = a("sea_lantern", new bvr(cfi.c.a(cxd.E, cxe.p).d(0.3F).a(cbh.g).a(cfj -> 15)));
	public static final bvr gA = a("hay_block", new bym(cfi.c.a(cxd.s, cxe.t).d(0.5F).a(cbh.c)));
	public static final bvr gB = a("white_carpet", new cda(bje.WHITE, cfi.c.a(cxd.d, cxe.j).d(0.1F).a(cbh.h)));
	public static final bvr gC = a("orange_carpet", new cda(bje.ORANGE, cfi.c.a(cxd.d, cxe.q).d(0.1F).a(cbh.h)));
	public static final bvr gD = a("magenta_carpet", new cda(bje.MAGENTA, cfi.c.a(cxd.d, cxe.r).d(0.1F).a(cbh.h)));
	public static final bvr gE = a("light_blue_carpet", new cda(bje.LIGHT_BLUE, cfi.c.a(cxd.d, cxe.s).d(0.1F).a(cbh.h)));
	public static final bvr gF = a("yellow_carpet", new cda(bje.YELLOW, cfi.c.a(cxd.d, cxe.t).d(0.1F).a(cbh.h)));
	public static final bvr gG = a("lime_carpet", new cda(bje.LIME, cfi.c.a(cxd.d, cxe.u).d(0.1F).a(cbh.h)));
	public static final bvr gH = a("pink_carpet", new cda(bje.PINK, cfi.c.a(cxd.d, cxe.v).d(0.1F).a(cbh.h)));
	public static final bvr gI = a("gray_carpet", new cda(bje.GRAY, cfi.c.a(cxd.d, cxe.w).d(0.1F).a(cbh.h)));
	public static final bvr gJ = a("light_gray_carpet", new cda(bje.LIGHT_GRAY, cfi.c.a(cxd.d, cxe.x).d(0.1F).a(cbh.h)));
	public static final bvr gK = a("cyan_carpet", new cda(bje.CYAN, cfi.c.a(cxd.d, cxe.y).d(0.1F).a(cbh.h)));
	public static final bvr gL = a("purple_carpet", new cda(bje.PURPLE, cfi.c.a(cxd.d, cxe.z).d(0.1F).a(cbh.h)));
	public static final bvr gM = a("blue_carpet", new cda(bje.BLUE, cfi.c.a(cxd.d, cxe.A).d(0.1F).a(cbh.h)));
	public static final bvr gN = a("brown_carpet", new cda(bje.BROWN, cfi.c.a(cxd.d, cxe.B).d(0.1F).a(cbh.h)));
	public static final bvr gO = a("green_carpet", new cda(bje.GREEN, cfi.c.a(cxd.d, cxe.C).d(0.1F).a(cbh.h)));
	public static final bvr gP = a("red_carpet", new cda(bje.RED, cfi.c.a(cxd.d, cxe.D).d(0.1F).a(cbh.h)));
	public static final bvr gQ = a("black_carpet", new cda(bje.BLACK, cfi.c.a(cxd.d, cxe.E).d(0.1F).a(cbh.h)));
	public static final bvr gR = a("terracotta", new bvr(cfi.c.a(cxd.H, cxe.q).h().a(1.25F, 4.2F)));
	public static final bvr gS = a("coal_block", new bvr(cfi.c.a(cxd.H, cxe.E).h().a(5.0F, 6.0F)));
	public static final bvr gT = a("packed_ice", new bvr(cfi.c.a(cxd.t).a(0.98F).d(0.5F).a(cbh.g)));
	public static final bvr gU = a("sunflower", new cbx(cfi.c.a(cxd.g).a().c().a(cbh.c)));
	public static final bvr gV = a("lilac", new cbx(cfi.c.a(cxd.g).a().c().a(cbh.c)));
	public static final bvr gW = a("rose_bush", new cbx(cfi.c.a(cxd.g).a().c().a(cbh.c)));
	public static final bvr gX = a("peony", new cbx(cfi.c.a(cxd.g).a().c().a(cbh.c)));
	public static final bvr gY = a("tall_grass", new bxg(cfi.c.a(cxd.g).a().c().a(cbh.c)));
	public static final bvr gZ = a("large_fern", new bxg(cfi.c.a(cxd.g).a().c().a(cbh.c)));
	public static final bvr ha = a("white_banner", new buz(bje.WHITE, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hb = a("orange_banner", new buz(bje.ORANGE, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hc = a("magenta_banner", new buz(bje.MAGENTA, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hd = a("light_blue_banner", new buz(bje.LIGHT_BLUE, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr he = a("yellow_banner", new buz(bje.YELLOW, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hf = a("lime_banner", new buz(bje.LIME, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hg = a("pink_banner", new buz(bje.PINK, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hh = a("gray_banner", new buz(bje.GRAY, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hi = a("light_gray_banner", new buz(bje.LIGHT_GRAY, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hj = a("cyan_banner", new buz(bje.CYAN, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hk = a("purple_banner", new buz(bje.PURPLE, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hl = a("blue_banner", new buz(bje.BLUE, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hm = a("brown_banner", new buz(bje.BROWN, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hn = a("green_banner", new buz(bje.GREEN, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr ho = a("red_banner", new buz(bje.RED, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hp = a("black_banner", new buz(bje.BLACK, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a)));
	public static final bvr hq = a("white_wall_banner", new ccl(bje.WHITE, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(ha)));
	public static final bvr hr = a("orange_wall_banner", new ccl(bje.ORANGE, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(hb)));
	public static final bvr hs = a("magenta_wall_banner", new ccl(bje.MAGENTA, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(hc)));
	public static final bvr ht = a("light_blue_wall_banner", new ccl(bje.LIGHT_BLUE, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(hd)));
	public static final bvr hu = a("yellow_wall_banner", new ccl(bje.YELLOW, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(he)));
	public static final bvr hv = a("lime_wall_banner", new ccl(bje.LIME, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(hf)));
	public static final bvr hw = a("pink_wall_banner", new ccl(bje.PINK, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(hg)));
	public static final bvr hx = a("gray_wall_banner", new ccl(bje.GRAY, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(hh)));
	public static final bvr hy = a("light_gray_wall_banner", new ccl(bje.LIGHT_GRAY, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(hi)));
	public static final bvr hz = a("cyan_wall_banner", new ccl(bje.CYAN, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(hj)));
	public static final bvr hA = a("purple_wall_banner", new ccl(bje.PURPLE, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(hk)));
	public static final bvr hB = a("blue_wall_banner", new ccl(bje.BLUE, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(hl)));
	public static final bvr hC = a("brown_wall_banner", new ccl(bje.BROWN, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(hm)));
	public static final bvr hD = a("green_wall_banner", new ccl(bje.GREEN, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(hn)));
	public static final bvr hE = a("red_wall_banner", new ccl(bje.RED, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(ho)));
	public static final bvr hF = a("black_wall_banner", new ccl(bje.BLACK, cfi.c.a(cxd.x).a().d(1.0F).a(cbh.a).a(hp)));
	public static final bvr hG = a("red_sandstone", new bvr(cfi.c.a(cxd.H, cxe.q).h().d(0.8F)));
	public static final bvr hH = a("chiseled_red_sandstone", new bvr(cfi.c.a(cxd.H, cxe.q).h().d(0.8F)));
	public static final bvr hI = a("cut_red_sandstone", new bvr(cfi.c.a(cxd.H, cxe.q).h().d(0.8F)));
	public static final bvr hJ = a("red_sandstone_stairs", new cbn(hG.n(), cfi.c.a((cfi)hG)));
	public static final bvr hK = a("oak_slab", new caz(cfi.c.a(cxd.x, cxe.o).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr hL = a("spruce_slab", new caz(cfi.c.a(cxd.x, cxe.J).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr hM = a("birch_slab", new caz(cfi.c.a(cxd.x, cxe.d).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr hN = a("jungle_slab", new caz(cfi.c.a(cxd.x, cxe.l).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr hO = a("acacia_slab", new caz(cfi.c.a(cxd.x, cxe.q).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr hP = a("dark_oak_slab", new caz(cfi.c.a(cxd.x, cxe.B).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr hQ = a("stone_slab", new caz(cfi.c.a(cxd.H, cxe.m).h().a(2.0F, 6.0F)));
	public static final bvr hR = a("smooth_stone_slab", new caz(cfi.c.a(cxd.H, cxe.m).h().a(2.0F, 6.0F)));
	public static final bvr hS = a("sandstone_slab", new caz(cfi.c.a(cxd.H, cxe.d).h().a(2.0F, 6.0F)));
	public static final bvr hT = a("cut_sandstone_slab", new caz(cfi.c.a(cxd.H, cxe.d).h().a(2.0F, 6.0F)));
	public static final bvr hU = a("petrified_oak_slab", new caz(cfi.c.a(cxd.H, cxe.o).h().a(2.0F, 6.0F)));
	public static final bvr hV = a("cobblestone_slab", new caz(cfi.c.a(cxd.H, cxe.m).h().a(2.0F, 6.0F)));
	public static final bvr hW = a("brick_slab", new caz(cfi.c.a(cxd.H, cxe.D).h().a(2.0F, 6.0F)));
	public static final bvr hX = a("stone_brick_slab", new caz(cfi.c.a(cxd.H, cxe.m).h().a(2.0F, 6.0F)));
	public static final bvr hY = a("nether_brick_slab", new caz(cfi.c.a(cxd.H, cxe.K).h().a(2.0F, 6.0F).a(cbh.L)));
	public static final bvr hZ = a("quartz_slab", new caz(cfi.c.a(cxd.H, cxe.p).h().a(2.0F, 6.0F)));
	public static final bvr ia = a("red_sandstone_slab", new caz(cfi.c.a(cxd.H, cxe.q).h().a(2.0F, 6.0F)));
	public static final bvr ib = a("cut_red_sandstone_slab", new caz(cfi.c.a(cxd.H, cxe.q).h().a(2.0F, 6.0F)));
	public static final bvr ic = a("purpur_slab", new caz(cfi.c.a(cxd.H, cxe.r).h().a(2.0F, 6.0F)));
	public static final bvr id = a("smooth_stone", new bvr(cfi.c.a(cxd.H, cxe.m).h().a(2.0F, 6.0F)));
	public static final bvr ie = a("smooth_sandstone", new bvr(cfi.c.a(cxd.H, cxe.d).h().a(2.0F, 6.0F)));
	public static final bvr if = a("smooth_quartz", new bvr(cfi.c.a(cxd.H, cxe.p).h().a(2.0F, 6.0F)));
	public static final bvr ig = a("smooth_red_sandstone", new bvr(cfi.c.a(cxd.H, cxe.q).h().a(2.0F, 6.0F)));
	public static final bvr ih = a("spruce_fence_gate", new bxu(cfi.c.a(cxd.x, o.s()).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr ii = a("birch_fence_gate", new bxu(cfi.c.a(cxd.x, p.s()).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr ij = a("jungle_fence_gate", new bxu(cfi.c.a(cxd.x, q.s()).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr ik = a("acacia_fence_gate", new bxu(cfi.c.a(cxd.x, r.s()).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr il = a("dark_oak_fence_gate", new bxu(cfi.c.a(cxd.x, s.s()).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr im = a("spruce_fence", new bxt(cfi.c.a(cxd.x, o.s()).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr in = a("birch_fence", new bxt(cfi.c.a(cxd.x, p.s()).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr io = a("jungle_fence", new bxt(cfi.c.a(cxd.x, q.s()).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr ip = a("acacia_fence", new bxt(cfi.c.a(cxd.x, r.s()).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr iq = a("dark_oak_fence", new bxt(cfi.c.a(cxd.x, s.s()).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr ir = a("spruce_door", new bxe(cfi.c.a(cxd.x, o.s()).d(3.0F).a(cbh.a).b()));
	public static final bvr is = a("birch_door", new bxe(cfi.c.a(cxd.x, p.s()).d(3.0F).a(cbh.a).b()));
	public static final bvr it = a("jungle_door", new bxe(cfi.c.a(cxd.x, q.s()).d(3.0F).a(cbh.a).b()));
	public static final bvr iu = a("acacia_door", new bxe(cfi.c.a(cxd.x, r.s()).d(3.0F).a(cbh.a).b()));
	public static final bvr iv = a("dark_oak_door", new bxe(cfi.c.a(cxd.x, s.s()).d(3.0F).a(cbh.a).b()));
	public static final bvr iw = a("end_rod", new bxn(cfi.c.a(cxd.n).c().a(cfj -> 14).a(cbh.a).b()));
	public static final bvr ix = a("chorus_plant", new bwj(cfi.c.a(cxd.e, cxe.z).d(0.4F).a(cbh.a).b()));
	public static final bvr iy = a("chorus_flower", new bwi((bwj)ix, cfi.c.a(cxd.e, cxe.z).d().d(0.4F).a(cbh.a).b()));
	public static final bvr iz = a("purpur_block", new bvr(cfi.c.a(cxd.H, cxe.r).h().a(1.5F, 6.0F)));
	public static final bvr iA = a("purpur_pillar", new cao(cfi.c.a(cxd.H, cxe.r).h().a(1.5F, 6.0F)));
	public static final bvr iB = a("purpur_stairs", new cbn(iz.n(), cfi.c.a((cfi)iz)));
	public static final bvr iC = a("end_stone_bricks", new bvr(cfi.c.a(cxd.H, cxe.d).h().a(3.0F, 9.0F)));
	public static final bvr iD = a("beetroots", new bvo(cfi.c.a(cxd.e).a().d().c().a(cbh.u)));
	public static final bvr iE = a("grass_path", new byf(cfi.c.a(cxd.r).d(0.65F).a(cbh.c).c(bvs::a)));
	public static final bvr iF = a("end_gateway", new bxk(cfi.c.a(cxd.c, cxe.E).a().a(cfj -> 15).a(-1.0F, 3600000.0F).f()));
	public static final bvr iG = a("repeating_command_block", new bwl(cfi.c.a(cxd.I, cxe.z).h().a(-1.0F, 3600000.0F).f()));
	public static final bvr iH = a("chain_command_block", new bwl(cfi.c.a(cxd.I, cxe.C).h().a(-1.0F, 3600000.0F).f()));
	public static final bvr iI = a(
		"frosted_ice", new bxz(cfi.c.a(cxd.F).a(0.98F).d().d(0.5F).a(cbh.g).b().a((cfi.d<aoq<?>>)((cfj, bpg, fu, aoq) -> aoq == aoq.ak)))
	);
	public static final bvr iJ = a(
		"magma_block", new bzh(cfi.c.a(cxd.H, cxe.K).h().a(cfj -> 3).d().d(0.5F).a((cfi.d<aoq<?>>)((cfj, bpg, fu, aoq) -> aoq.c())).d(bvs::a).e(bvs::a))
	);
	public static final bvr iK = a("nether_wart_block", new bvr(cfi.c.a(cxd.s, cxe.D).d(1.0F).a(cbh.J)));
	public static final bvr iL = a("red_nether_bricks", new bvr(cfi.c.a(cxd.H, cxe.K).h().a(2.0F, 6.0F).a(cbh.L)));
	public static final bvr iM = a("bone_block", new cao(cfi.c.a(cxd.H, cxe.d).h().d(2.0F).a(cbh.O)));
	public static final bvr iN = a("structure_void", new cbu(cfi.c.a(cxd.b).a().f()));
	public static final bvr iO = a("observer", new bzt(cfi.c.a(cxd.H).d(3.0F).h().a(bvs::b)));
	public static final bvr iP = a("shulker_box", a(null, cfi.c.a(cxd.w)));
	public static final bvr iQ = a("white_shulker_box", a(bje.WHITE, cfi.c.a(cxd.w, cxe.j)));
	public static final bvr iR = a("orange_shulker_box", a(bje.ORANGE, cfi.c.a(cxd.w, cxe.q)));
	public static final bvr iS = a("magenta_shulker_box", a(bje.MAGENTA, cfi.c.a(cxd.w, cxe.r)));
	public static final bvr iT = a("light_blue_shulker_box", a(bje.LIGHT_BLUE, cfi.c.a(cxd.w, cxe.s)));
	public static final bvr iU = a("yellow_shulker_box", a(bje.YELLOW, cfi.c.a(cxd.w, cxe.t)));
	public static final bvr iV = a("lime_shulker_box", a(bje.LIME, cfi.c.a(cxd.w, cxe.u)));
	public static final bvr iW = a("pink_shulker_box", a(bje.PINK, cfi.c.a(cxd.w, cxe.v)));
	public static final bvr iX = a("gray_shulker_box", a(bje.GRAY, cfi.c.a(cxd.w, cxe.w)));
	public static final bvr iY = a("light_gray_shulker_box", a(bje.LIGHT_GRAY, cfi.c.a(cxd.w, cxe.x)));
	public static final bvr iZ = a("cyan_shulker_box", a(bje.CYAN, cfi.c.a(cxd.w, cxe.y)));
	public static final bvr ja = a("purple_shulker_box", a(bje.PURPLE, cfi.c.a(cxd.w, cxe.V)));
	public static final bvr jb = a("blue_shulker_box", a(bje.BLUE, cfi.c.a(cxd.w, cxe.A)));
	public static final bvr jc = a("brown_shulker_box", a(bje.BROWN, cfi.c.a(cxd.w, cxe.B)));
	public static final bvr jd = a("green_shulker_box", a(bje.GREEN, cfi.c.a(cxd.w, cxe.C)));
	public static final bvr je = a("red_shulker_box", a(bje.RED, cfi.c.a(cxd.w, cxe.D)));
	public static final bvr jf = a("black_shulker_box", a(bje.BLACK, cfi.c.a(cxd.w, cxe.E)));
	public static final bvr jg = a("white_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.WHITE).h().d(1.4F)));
	public static final bvr jh = a("orange_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.ORANGE).h().d(1.4F)));
	public static final bvr ji = a("magenta_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.MAGENTA).h().d(1.4F)));
	public static final bvr jj = a("light_blue_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.LIGHT_BLUE).h().d(1.4F)));
	public static final bvr jk = a("yellow_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.YELLOW).h().d(1.4F)));
	public static final bvr jl = a("lime_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.LIME).h().d(1.4F)));
	public static final bvr jm = a("pink_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.PINK).h().d(1.4F)));
	public static final bvr jn = a("gray_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.GRAY).h().d(1.4F)));
	public static final bvr jo = a("light_gray_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.LIGHT_GRAY).h().d(1.4F)));
	public static final bvr jp = a("cyan_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.CYAN).h().d(1.4F)));
	public static final bvr jq = a("purple_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.PURPLE).h().d(1.4F)));
	public static final bvr jr = a("blue_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.BLUE).h().d(1.4F)));
	public static final bvr js = a("brown_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.BROWN).h().d(1.4F)));
	public static final bvr jt = a("green_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.GREEN).h().d(1.4F)));
	public static final bvr ju = a("red_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.RED).h().d(1.4F)));
	public static final bvr jv = a("black_glazed_terracotta", new byd(cfi.c.a(cxd.H, bje.BLACK).h().d(1.4F)));
	public static final bvr jw = a("white_concrete", new bvr(cfi.c.a(cxd.H, bje.WHITE).h().d(1.8F)));
	public static final bvr jx = a("orange_concrete", new bvr(cfi.c.a(cxd.H, bje.ORANGE).h().d(1.8F)));
	public static final bvr jy = a("magenta_concrete", new bvr(cfi.c.a(cxd.H, bje.MAGENTA).h().d(1.8F)));
	public static final bvr jz = a("light_blue_concrete", new bvr(cfi.c.a(cxd.H, bje.LIGHT_BLUE).h().d(1.8F)));
	public static final bvr jA = a("yellow_concrete", new bvr(cfi.c.a(cxd.H, bje.YELLOW).h().d(1.8F)));
	public static final bvr jB = a("lime_concrete", new bvr(cfi.c.a(cxd.H, bje.LIME).h().d(1.8F)));
	public static final bvr jC = a("pink_concrete", new bvr(cfi.c.a(cxd.H, bje.PINK).h().d(1.8F)));
	public static final bvr jD = a("gray_concrete", new bvr(cfi.c.a(cxd.H, bje.GRAY).h().d(1.8F)));
	public static final bvr jE = a("light_gray_concrete", new bvr(cfi.c.a(cxd.H, bje.LIGHT_GRAY).h().d(1.8F)));
	public static final bvr jF = a("cyan_concrete", new bvr(cfi.c.a(cxd.H, bje.CYAN).h().d(1.8F)));
	public static final bvr jG = a("purple_concrete", new bvr(cfi.c.a(cxd.H, bje.PURPLE).h().d(1.8F)));
	public static final bvr jH = a("blue_concrete", new bvr(cfi.c.a(cxd.H, bje.BLUE).h().d(1.8F)));
	public static final bvr jI = a("brown_concrete", new bvr(cfi.c.a(cxd.H, bje.BROWN).h().d(1.8F)));
	public static final bvr jJ = a("green_concrete", new bvr(cfi.c.a(cxd.H, bje.GREEN).h().d(1.8F)));
	public static final bvr jK = a("red_concrete", new bvr(cfi.c.a(cxd.H, bje.RED).h().d(1.8F)));
	public static final bvr jL = a("black_concrete", new bvr(cfi.c.a(cxd.H, bje.BLACK).h().d(1.8F)));
	public static final bvr jM = a("white_concrete_powder", new bwo(jw, cfi.c.a(cxd.u, bje.WHITE).d(0.5F).a(cbh.i)));
	public static final bvr jN = a("orange_concrete_powder", new bwo(jx, cfi.c.a(cxd.u, bje.ORANGE).d(0.5F).a(cbh.i)));
	public static final bvr jO = a("magenta_concrete_powder", new bwo(jy, cfi.c.a(cxd.u, bje.MAGENTA).d(0.5F).a(cbh.i)));
	public static final bvr jP = a("light_blue_concrete_powder", new bwo(jz, cfi.c.a(cxd.u, bje.LIGHT_BLUE).d(0.5F).a(cbh.i)));
	public static final bvr jQ = a("yellow_concrete_powder", new bwo(jA, cfi.c.a(cxd.u, bje.YELLOW).d(0.5F).a(cbh.i)));
	public static final bvr jR = a("lime_concrete_powder", new bwo(jB, cfi.c.a(cxd.u, bje.LIME).d(0.5F).a(cbh.i)));
	public static final bvr jS = a("pink_concrete_powder", new bwo(jC, cfi.c.a(cxd.u, bje.PINK).d(0.5F).a(cbh.i)));
	public static final bvr jT = a("gray_concrete_powder", new bwo(jD, cfi.c.a(cxd.u, bje.GRAY).d(0.5F).a(cbh.i)));
	public static final bvr jU = a("light_gray_concrete_powder", new bwo(jE, cfi.c.a(cxd.u, bje.LIGHT_GRAY).d(0.5F).a(cbh.i)));
	public static final bvr jV = a("cyan_concrete_powder", new bwo(jF, cfi.c.a(cxd.u, bje.CYAN).d(0.5F).a(cbh.i)));
	public static final bvr jW = a("purple_concrete_powder", new bwo(jG, cfi.c.a(cxd.u, bje.PURPLE).d(0.5F).a(cbh.i)));
	public static final bvr jX = a("blue_concrete_powder", new bwo(jH, cfi.c.a(cxd.u, bje.BLUE).d(0.5F).a(cbh.i)));
	public static final bvr jY = a("brown_concrete_powder", new bwo(jI, cfi.c.a(cxd.u, bje.BROWN).d(0.5F).a(cbh.i)));
	public static final bvr jZ = a("green_concrete_powder", new bwo(jJ, cfi.c.a(cxd.u, bje.GREEN).d(0.5F).a(cbh.i)));
	public static final bvr ka = a("red_concrete_powder", new bwo(jK, cfi.c.a(cxd.u, bje.RED).d(0.5F).a(cbh.i)));
	public static final bvr kb = a("black_concrete_powder", new bwo(jL, cfi.c.a(cxd.u, bje.BLACK).d(0.5F).a(cbh.i)));
	public static final bvr kc = a("kelp", new byw(cfi.c.a(cxd.f).a().d().c().a(cbh.o)));
	public static final bvr kd = a("kelp_plant", new byx(cfi.c.a(cxd.f).a().c().a(cbh.o)));
	public static final bvr ke = a("dried_kelp_block", new bvr(cfi.c.a(cxd.s, cxe.C).a(0.5F, 2.5F).a(cbh.c)));
	public static final bvr kf = a("turtle_egg", new cch(cfi.c.a(cxd.P, cxe.d).d(0.5F).a(cbh.f).d().b()));
	public static final bvr kg = a("dead_tube_coral_block", new bvr(cfi.c.a(cxd.H, cxe.w).h().a(1.5F, 6.0F)));
	public static final bvr kh = a("dead_brain_coral_block", new bvr(cfi.c.a(cxd.H, cxe.w).h().a(1.5F, 6.0F)));
	public static final bvr ki = a("dead_bubble_coral_block", new bvr(cfi.c.a(cxd.H, cxe.w).h().a(1.5F, 6.0F)));
	public static final bvr kj = a("dead_fire_coral_block", new bvr(cfi.c.a(cxd.H, cxe.w).h().a(1.5F, 6.0F)));
	public static final bvr kk = a("dead_horn_coral_block", new bvr(cfi.c.a(cxd.H, cxe.w).h().a(1.5F, 6.0F)));
	public static final bvr kl = a("tube_coral_block", new bwq(kg, cfi.c.a(cxd.H, cxe.A).h().a(1.5F, 6.0F).a(cbh.p)));
	public static final bvr km = a("brain_coral_block", new bwq(kh, cfi.c.a(cxd.H, cxe.v).h().a(1.5F, 6.0F).a(cbh.p)));
	public static final bvr kn = a("bubble_coral_block", new bwq(ki, cfi.c.a(cxd.H, cxe.z).h().a(1.5F, 6.0F).a(cbh.p)));
	public static final bvr ko = a("fire_coral_block", new bwq(kj, cfi.c.a(cxd.H, cxe.D).h().a(1.5F, 6.0F).a(cbh.p)));
	public static final bvr kp = a("horn_coral_block", new bwq(kk, cfi.c.a(cxd.H, cxe.t).h().a(1.5F, 6.0F).a(cbh.p)));
	public static final bvr kq = a("dead_tube_coral", new bvd(cfi.c.a(cxd.H, cxe.w).h().a().c()));
	public static final bvr kr = a("dead_brain_coral", new bvd(cfi.c.a(cxd.H, cxe.w).h().a().c()));
	public static final bvr ks = a("dead_bubble_coral", new bvd(cfi.c.a(cxd.H, cxe.w).h().a().c()));
	public static final bvr kt = a("dead_fire_coral", new bvd(cfi.c.a(cxd.H, cxe.w).h().a().c()));
	public static final bvr ku = a("dead_horn_coral", new bvd(cfi.c.a(cxd.H, cxe.w).h().a().c()));
	public static final bvr kv = a("tube_coral", new bws(kq, cfi.c.a(cxd.f, cxe.A).a().c().a(cbh.o)));
	public static final bvr kw = a("brain_coral", new bws(kr, cfi.c.a(cxd.f, cxe.v).a().c().a(cbh.o)));
	public static final bvr kx = a("bubble_coral", new bws(ks, cfi.c.a(cxd.f, cxe.z).a().c().a(cbh.o)));
	public static final bvr ky = a("fire_coral", new bws(kt, cfi.c.a(cxd.f, cxe.D).a().c().a(cbh.o)));
	public static final bvr kz = a("horn_coral", new bws(ku, cfi.c.a(cxd.f, cxe.t).a().c().a(cbh.o)));
	public static final bvr kA = a("dead_tube_coral_fan", new bvc(cfi.c.a(cxd.H, cxe.w).h().a().c()));
	public static final bvr kB = a("dead_brain_coral_fan", new bvc(cfi.c.a(cxd.H, cxe.w).h().a().c()));
	public static final bvr kC = a("dead_bubble_coral_fan", new bvc(cfi.c.a(cxd.H, cxe.w).h().a().c()));
	public static final bvr kD = a("dead_fire_coral_fan", new bvc(cfi.c.a(cxd.H, cxe.w).h().a().c()));
	public static final bvr kE = a("dead_horn_coral_fan", new bvc(cfi.c.a(cxd.H, cxe.w).h().a().c()));
	public static final bvr kF = a("tube_coral_fan", new bwr(kA, cfi.c.a(cxd.f, cxe.A).a().c().a(cbh.o)));
	public static final bvr kG = a("brain_coral_fan", new bwr(kB, cfi.c.a(cxd.f, cxe.v).a().c().a(cbh.o)));
	public static final bvr kH = a("bubble_coral_fan", new bwr(kC, cfi.c.a(cxd.f, cxe.z).a().c().a(cbh.o)));
	public static final bvr kI = a("fire_coral_fan", new bwr(kD, cfi.c.a(cxd.f, cxe.D).a().c().a(cbh.o)));
	public static final bvr kJ = a("horn_coral_fan", new bwr(kE, cfi.c.a(cxd.f, cxe.t).a().c().a(cbh.o)));
	public static final bvr kK = a("dead_tube_coral_wall_fan", new bvf(cfi.c.a(cxd.H, cxe.w).h().a().c().a(kA)));
	public static final bvr kL = a("dead_brain_coral_wall_fan", new bvf(cfi.c.a(cxd.H, cxe.w).h().a().c().a(kB)));
	public static final bvr kM = a("dead_bubble_coral_wall_fan", new bvf(cfi.c.a(cxd.H, cxe.w).h().a().c().a(kC)));
	public static final bvr kN = a("dead_fire_coral_wall_fan", new bvf(cfi.c.a(cxd.H, cxe.w).h().a().c().a(kD)));
	public static final bvr kO = a("dead_horn_coral_wall_fan", new bvf(cfi.c.a(cxd.H, cxe.w).h().a().c().a(kE)));
	public static final bvr kP = a("tube_coral_wall_fan", new bwt(kK, cfi.c.a(cxd.f, cxe.A).a().c().a(cbh.o).a(kF)));
	public static final bvr kQ = a("brain_coral_wall_fan", new bwt(kL, cfi.c.a(cxd.f, cxe.v).a().c().a(cbh.o).a(kG)));
	public static final bvr kR = a("bubble_coral_wall_fan", new bwt(kM, cfi.c.a(cxd.f, cxe.z).a().c().a(cbh.o).a(kH)));
	public static final bvr kS = a("fire_coral_wall_fan", new bwt(kN, cfi.c.a(cxd.f, cxe.D).a().c().a(cbh.o).a(kI)));
	public static final bvr kT = a("horn_coral_wall_fan", new bwt(kO, cfi.c.a(cxd.f, cxe.t).a().c().a(cbh.o).a(kJ)));
	public static final bvr kU = a("sea_pickle", new cat(cfi.c.a(cxd.f, cxe.C).a(cfj -> cat.h(cfj) ? 0 : 3 + 3 * (Integer)cfj.c(cat.a)).a(cbh.m).b()));
	public static final bvr kV = a("blue_ice", new byl(cfi.c.a(cxd.t).d(2.8F).a(0.989F).a(cbh.g)));
	public static final bvr kW = a("conduit", new bwp(cfi.c.a(cxd.E, cxe.G).d(3.0F).a(cfj -> 15).b()));
	public static final bvr kX = a("bamboo_sapling", new buy(cfi.c.a(cxd.z).d().c().a().d(1.0F).a(cbh.r)));
	public static final bvr kY = a("bamboo", new bux(cfi.c.a(cxd.A, cxe.i).d().c().d(1.0F).a(cbh.q).b()));
	public static final bvr kZ = a("potted_bamboo", new bxy(kY, cfi.c.a(cxd.n).c().b()));
	public static final bvr la = a("void_air", new buu(cfi.c.a(cxd.a).a().f().g()));
	public static final bvr lb = a("cave_air", new buu(cfi.c.a(cxd.a).a().f().g()));
	public static final bvr lc = a("bubble_column", new bvv(cfi.c.a(cxd.j).a().f()));
	public static final bvr ld = a("polished_granite_stairs", new cbn(d.n(), cfi.c.a((cfi)d)));
	public static final bvr le = a("smooth_red_sandstone_stairs", new cbn(ig.n(), cfi.c.a((cfi)ig)));
	public static final bvr lf = a("mossy_stone_brick_stairs", new cbn(dv.n(), cfi.c.a((cfi)dv)));
	public static final bvr lg = a("polished_diorite_stairs", new cbn(f.n(), cfi.c.a((cfi)f)));
	public static final bvr lh = a("mossy_cobblestone_stairs", new cbn(bJ.n(), cfi.c.a((cfi)bJ)));
	public static final bvr li = a("end_stone_brick_stairs", new cbn(iC.n(), cfi.c.a((cfi)iC)));
	public static final bvr lj = a("stone_stairs", new cbn(b.n(), cfi.c.a((cfi)b)));
	public static final bvr lk = a("smooth_sandstone_stairs", new cbn(ie.n(), cfi.c.a((cfi)ie)));
	public static final bvr ll = a("smooth_quartz_stairs", new cbn(if.n(), cfi.c.a((cfi)if)));
	public static final bvr lm = a("granite_stairs", new cbn(c.n(), cfi.c.a((cfi)c)));
	public static final bvr ln = a("andesite_stairs", new cbn(g.n(), cfi.c.a((cfi)g)));
	public static final bvr lo = a("red_nether_brick_stairs", new cbn(iL.n(), cfi.c.a((cfi)iL)));
	public static final bvr lp = a("polished_andesite_stairs", new cbn(h.n(), cfi.c.a((cfi)h)));
	public static final bvr lq = a("diorite_stairs", new cbn(e.n(), cfi.c.a((cfi)e)));
	public static final bvr lr = a("polished_granite_slab", new caz(cfi.c.a((cfi)d)));
	public static final bvr ls = a("smooth_red_sandstone_slab", new caz(cfi.c.a((cfi)ig)));
	public static final bvr lt = a("mossy_stone_brick_slab", new caz(cfi.c.a((cfi)dv)));
	public static final bvr lu = a("polished_diorite_slab", new caz(cfi.c.a((cfi)f)));
	public static final bvr lv = a("mossy_cobblestone_slab", new caz(cfi.c.a((cfi)bJ)));
	public static final bvr lw = a("end_stone_brick_slab", new caz(cfi.c.a((cfi)iC)));
	public static final bvr lx = a("smooth_sandstone_slab", new caz(cfi.c.a((cfi)ie)));
	public static final bvr ly = a("smooth_quartz_slab", new caz(cfi.c.a((cfi)if)));
	public static final bvr lz = a("granite_slab", new caz(cfi.c.a((cfi)c)));
	public static final bvr lA = a("andesite_slab", new caz(cfi.c.a((cfi)g)));
	public static final bvr lB = a("red_nether_brick_slab", new caz(cfi.c.a((cfi)iL)));
	public static final bvr lC = a("polished_andesite_slab", new caz(cfi.c.a((cfi)h)));
	public static final bvr lD = a("diorite_slab", new caz(cfi.c.a((cfi)e)));
	public static final bvr lE = a("brick_wall", new ccm(cfi.c.a((cfi)bG)));
	public static final bvr lF = a("prismarine_wall", new ccm(cfi.c.a((cfi)gq)));
	public static final bvr lG = a("red_sandstone_wall", new ccm(cfi.c.a((cfi)hG)));
	public static final bvr lH = a("mossy_stone_brick_wall", new ccm(cfi.c.a((cfi)dv)));
	public static final bvr lI = a("granite_wall", new ccm(cfi.c.a((cfi)c)));
	public static final bvr lJ = a("stone_brick_wall", new ccm(cfi.c.a((cfi)du)));
	public static final bvr lK = a("nether_brick_wall", new ccm(cfi.c.a((cfi)dV)));
	public static final bvr lL = a("andesite_wall", new ccm(cfi.c.a((cfi)g)));
	public static final bvr lM = a("red_nether_brick_wall", new ccm(cfi.c.a((cfi)iL)));
	public static final bvr lN = a("sandstone_wall", new ccm(cfi.c.a((cfi)at)));
	public static final bvr lO = a("end_stone_brick_wall", new ccm(cfi.c.a((cfi)iC)));
	public static final bvr lP = a("diorite_wall", new ccm(cfi.c.a((cfi)e)));
	public static final bvr lQ = a("scaffolding", new cas(cfi.c.a(cxd.n, cxe.d).a().a(cbh.s).e()));
	public static final bvr lR = a("loom", new bzg(cfi.c.a(cxd.x).d(2.5F).a(cbh.a)));
	public static final bvr lS = a("barrel", new bva(cfi.c.a(cxd.x).d(2.5F).a(cbh.a)));
	public static final bvr lT = a("smoker", new cbc(cfi.c.a(cxd.H).h().d(3.5F).a(a(13))));
	public static final bvr lU = a("blast_furnace", new bvq(cfi.c.a(cxd.H).h().d(3.5F).a(a(13))));
	public static final bvr lV = a("cartography_table", new bwd(cfi.c.a(cxd.x).d(2.5F).a(cbh.a)));
	public static final bvr lW = a("fletching_table", new bxw(cfi.c.a(cxd.x).d(2.5F).a(cbh.a)));
	public static final bvr lX = a("grindstone", new byh(cfi.c.a(cxd.K, cxe.h).h().a(2.0F, 6.0F).a(cbh.e)));
	public static final bvr lY = a("lectern", new bzb(cfi.c.a(cxd.x).d(2.5F).a(cbh.a)));
	public static final bvr lZ = a("smithing_table", new cbb(cfi.c.a(cxd.x).d(2.5F).a(cbh.a)));
	public static final bvr ma = a("stonecutter", new cbs(cfi.c.a(cxd.H).h().d(3.5F)));
	public static final bvr mb = a("bell", new bvp(cfi.c.a(cxd.I, cxe.F).h().d(5.0F).a(cbh.l)));
	public static final bvr mc = a("lantern", new byz(cfi.c.a(cxd.I).h().d(3.5F).a(cbh.y).a(cfj -> 15).b()));
	public static final bvr md = a("soul_lantern", new byz(cfi.c.a(cxd.I).h().d(3.5F).a(cbh.y).a(cfj -> 10).b()));
	public static final bvr me = a("campfire", new bwb(true, 1, cfi.c.a(cxd.x, cxe.J).d(2.0F).a(cbh.a).a(a(15)).b()));
	public static final bvr mf = a("soul_campfire", new bwb(false, 2, cfi.c.a(cxd.x, cxe.J).d(2.0F).a(cbh.a).a(a(10)).b()));
	public static final bvr mg = a("sweet_berry_bush", new cbw(cfi.c.a(cxd.e).d().a().a(cbh.t)));
	public static final bvr mh = a("warped_stem", a(cxe.af));
	public static final bvr mi = a("stripped_warped_stem", a(cxe.af));
	public static final bvr mj = a("warped_hyphae", new cao(cfi.c.a(cxd.y, cxe.ag).d(2.0F).a(cbh.z)));
	public static final bvr mk = a("stripped_warped_hyphae", new cao(cfi.c.a(cxd.y, cxe.ag).d(2.0F).a(cbh.z)));
	public static final bvr ml = a("warped_nylium", new bzs(cfi.c.a(cxd.H, cxe.ae).h().d(0.4F).a(cbh.A).d()));
	public static final bvr mm = a("warped_fungus", new bya(cfi.c.a(cxd.e, cxe.y).c().a().a(cbh.B), () -> ckt.L.b(cky.d)));
	public static final bvr mn = a("warped_wart_block", new bvr(cfi.c.a(cxd.s, cxe.ah).d(1.0F).a(cbh.J)));
	public static final bvr mo = a("warped_roots", new can(cfi.c.a(cxd.g, cxe.y).a().c().a(cbh.C)));
	public static final bvr mp = a("nether_sprouts", new bzn(cfi.c.a(cxd.g, cxe.y).a().c().a(cbh.M)));
	public static final bvr mq = a("crimson_stem", a(cxe.ac));
	public static final bvr mr = a("stripped_crimson_stem", a(cxe.ac));
	public static final bvr ms = a("crimson_hyphae", new cao(cfi.c.a(cxd.y, cxe.ad).d(2.0F).a(cbh.z)));
	public static final bvr mt = a("stripped_crimson_hyphae", new cao(cfi.c.a(cxd.y, cxe.ad).d(2.0F).a(cbh.z)));
	public static final bvr mu = a("crimson_nylium", new bzs(cfi.c.a(cxd.H, cxe.ab).h().d(0.4F).a(cbh.A).d()));
	public static final bvr mv = a("crimson_fungus", new bya(cfi.c.a(cxd.e, cxe.K).c().a().a(cbh.B), () -> ckt.L.b(cky.b)));
	public static final bvr mw = a("shroomlight", new bvr(cfi.c.a(cxd.s, cxe.D).d(1.0F).a(cbh.D).a(cfj -> 15)));
	public static final bvr mx = a("weeping_vines", new ccs(cfi.c.a(cxd.e, cxe.K).d().a().c().a(cbh.E)));
	public static final bvr my = a("weeping_vines_plant", new cct(cfi.c.a(cxd.e, cxe.K).a().c().a(cbh.E)));
	public static final bvr mz = a("twisting_vines", new cci(cfi.c.a(cxd.e, cxe.y).d().a().c().a(cbh.E)));
	public static final bvr mA = a("twisting_vines_plant", new ccj(cfi.c.a(cxd.e, cxe.y).a().c().a(cbh.E)));
	public static final bvr mB = a("crimson_roots", new can(cfi.c.a(cxd.g, cxe.K).a().c().a(cbh.C)));
	public static final bvr mC = a("crimson_planks", new bvr(cfi.c.a(cxd.y, cxe.ac).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr mD = a("warped_planks", new bvr(cfi.c.a(cxd.y, cxe.af).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr mE = a("crimson_slab", new caz(cfi.c.a(cxd.y, cxe.K).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr mF = a("warped_slab", new caz(cfi.c.a(cxd.y, cxe.y).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr mG = a("crimson_pressure_plate", new cab(cab.a.EVERYTHING, cfi.c.a(cxd.y, cxe.K).a().d(0.5F).a(cbh.a)));
	public static final bvr mH = a("warped_pressure_plate", new cab(cab.a.EVERYTHING, cfi.c.a(cxd.y, cxe.y).a().d(0.5F).a(cbh.a)));
	public static final bvr mI = a("crimson_fence", new bxt(cfi.c.a(cxd.y, cxe.K).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr mJ = a("warped_fence", new bxt(cfi.c.a(cxd.y, cxe.y).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr mK = a("crimson_trapdoor", new ccd(cfi.c.a(cxd.y, cxe.K).d(3.0F).a(cbh.a).b()));
	public static final bvr mL = a("warped_trapdoor", new ccd(cfi.c.a(cxd.y, cxe.y).d(3.0F).a(cbh.a).b()));
	public static final bvr mM = a("crimson_fence_gate", new bxu(cfi.c.a(cxd.y, cxe.K).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr mN = a("warped_fence_gate", new bxu(cfi.c.a(cxd.y, cxe.y).a(2.0F, 3.0F).a(cbh.a)));
	public static final bvr mO = a("crimson_stairs", new cbn(mC.n(), cfi.c.a((cfi)mC)));
	public static final bvr mP = a("warped_stairs", new cbn(mD.n(), cfi.c.a((cfi)mD)));
	public static final bvr mQ = a("crimson_button", new ccz(cfi.c.a(cxd.n).a().d(0.5F).a(cbh.a)));
	public static final bvr mR = a("warped_button", new ccz(cfi.c.a(cxd.n).a().d(0.5F).a(cbh.a)));
	public static final bvr mS = a("crimson_door", new bxe(cfi.c.a(cxd.y, mC.s()).d(3.0F).a(cbh.a).b()));
	public static final bvr mT = a("warped_door", new bxe(cfi.c.a(cxd.y, mD.s()).d(3.0F).a(cbh.a).b()));
	public static final bvr mU = a("crimson_sign", new cbo(cfi.c.a(cxd.y, cxe.K).a().d(1.0F).a(cbh.a), cgs.g));
	public static final bvr mV = a("warped_sign", new cbo(cfi.c.a(cxd.y, cxe.y).a().d(1.0F).a(cbh.a), cgs.h));
	public static final bvr mW = a("crimson_wall_sign", new ccn(cfi.c.a(cxd.y).a().d(1.0F).a(cbh.a).a(mU), cgs.g));
	public static final bvr mX = a("warped_wall_sign", new ccn(cfi.c.a(cxd.y).a().d(1.0F).a(cbh.a).a(mV), cgs.h));
	public static final bvr mY = a("structure_block", new cbt(cfi.c.a(cxd.I, cxe.x).h().a(-1.0F, 3600000.0F).f()));
	public static final bvr mZ = a("jigsaw", new byu(cfi.c.a(cxd.I, cxe.x).h().a(-1.0F, 3600000.0F).f()));
	public static final bvr na = a("composter", new bwn(cfi.c.a(cxd.x).d(0.6F).a(cbh.a)));
	public static final bvr nb = a("target", new cca(cfi.c.a(cxd.s, cxe.p).d(0.5F).a(cbh.c)));
	public static final bvr nc = a("bee_nest", new bvn(cfi.c.a(cxd.x, cxe.t).d(0.3F).a(cbh.a)));
	public static final bvr nd = a("beehive", new bvn(cfi.c.a(cxd.x).d(0.6F).a(cbh.a)));
	public static final bvr ne = a("honey_block", new byn(cfi.c.a(cxd.q, cxe.q).b(0.4F).c(0.5F).b().a(cbh.n)));
	public static final bvr nf = a("honeycomb_block", new bvr(cfi.c.a(cxd.q, cxe.q).d(0.6F).a(cbh.p)));
	public static final bvr ng = a("netherite_block", new bvr(cfi.c.a(cxd.I, cxe.E).h().a(50.0F, 1200.0F).a(cbh.P)));
	public static final bvr nh = a("ancient_debris", new bvr(cfi.c.a(cxd.I, cxe.E).h().a(30.0F, 1200.0F).a(cbh.Q)));
	public static final bvr ni = a("crying_obsidian", new bwx(cfi.c.a(cxd.H, cxe.E).h().a(50.0F, 1200.0F).a(cfj -> 10)));
	public static final bvr nj = a("respawn_anchor", new cam(cfi.c.a(cxd.H, cxe.E).h().a(50.0F, 1200.0F).a(cfj -> cam.a(cfj, 15))));
	public static final bvr nk = a("potted_crimson_fungus", new bxy(mv, cfi.c.a(cxd.n).c().b()));
	public static final bvr nl = a("potted_warped_fungus", new bxy(mm, cfi.c.a(cxd.n).c().b()));
	public static final bvr nm = a("potted_crimson_roots", new bxy(mB, cfi.c.a(cxd.n).c().b()));
	public static final bvr nn = a("potted_warped_roots", new bxy(mo, cfi.c.a(cxd.n).c().b()));
	public static final bvr no = a("lodestone", new bvr(cfi.c.a(cxd.K).h().d(3.5F).a(cbh.R)));
	public static final bvr np = a("blackstone", new bvr(cfi.c.a(cxd.H, cxe.E).h().a(1.5F, 6.0F)));
	public static final bvr nq = a("blackstone_stairs", new cbn(np.n(), cfi.c.a((cfi)np)));
	public static final bvr nr = a("blackstone_wall", new ccm(cfi.c.a((cfi)np)));
	public static final bvr ns = a("blackstone_slab", new caz(cfi.c.a((cfi)np).a(2.0F, 6.0F)));
	public static final bvr nt = a("polished_blackstone", new bvr(cfi.c.a((cfi)np).a(2.0F, 6.0F)));
	public static final bvr nu = a("polished_blackstone_bricks", new bvr(cfi.c.a((cfi)nt).a(1.5F, 6.0F)));
	public static final bvr nv = a("cracked_polished_blackstone_bricks", new bvr(cfi.c.a((cfi)nu)));
	public static final bvr nw = a("chiseled_polished_blackstone", new bvr(cfi.c.a((cfi)nt).a(1.5F, 6.0F)));
	public static final bvr nx = a("polished_blackstone_brick_slab", new caz(cfi.c.a((cfi)nu).a(2.0F, 6.0F)));
	public static final bvr ny = a("polished_blackstone_brick_stairs", new cbn(nu.n(), cfi.c.a((cfi)nu)));
	public static final bvr nz = a("polished_blackstone_brick_wall", new ccm(cfi.c.a((cfi)nu)));
	public static final bvr nA = a("gilded_blackstone", new bvr(cfi.c.a((cfi)np).a(cbh.U)));
	public static final bvr nB = a("polished_blackstone_stairs", new cbn(nt.n(), cfi.c.a((cfi)nt)));
	public static final bvr nC = a("polished_blackstone_slab", new caz(cfi.c.a((cfi)nt)));
	public static final bvr nD = a("polished_blackstone_pressure_plate", new cab(cab.a.MOBS, cfi.c.a(cxd.H, cxe.E).h().a().d(0.5F)));
	public static final bvr nE = a("polished_blackstone_button", new cbr(cfi.c.a(cxd.n).a().d(0.5F)));
	public static final bvr nF = a("polished_blackstone_wall", new ccm(cfi.c.a((cfi)nt)));
	public static final bvr nG = a("chiseled_nether_bricks", new bvr(cfi.c.a(cxd.H, cxe.K).h().a(2.0F, 6.0F).a(cbh.L)));
	public static final bvr nH = a("cracked_nether_bricks", new bvr(cfi.c.a(cxd.H, cxe.K).h().a(2.0F, 6.0F).a(cbh.L)));
	public static final bvr nI = a("quartz_bricks", new bvr(cfi.c.a((cfi)fz)));

	private static ToIntFunction<cfj> a(int integer) {
		return cfj -> cfj.c(cfz.r) ? integer : 0;
	}

	private static Boolean a(cfj cfj, bpg bpg, fu fu, aoq<?> aoq) {
		return false;
	}

	private static Boolean b(cfj cfj, bpg bpg, fu fu, aoq<?> aoq) {
		return true;
	}

	private static Boolean c(cfj cfj, bpg bpg, fu fu, aoq<?> aoq) {
		return aoq == aoq.ac || aoq == aoq.af;
	}

	private static bvm a(bje bje) {
		return new bvm(bje, cfi.c.a(cxd.B, cfj -> cfj.c(bvm.a) == cfx.FOOT ? bje.f() : cxe.e).a(cbh.a).d(0.2F).b());
	}

	private static cao a(cxe cxe1, cxe cxe2) {
		return new cao(cfi.c.a(cxd.x, cfj -> cfj.c(cao.a) == fz.a.Y ? cxe1 : cxe2).d(2.0F).a(cbh.a));
	}

	private static bvr a(cxe cxe) {
		return new cao(cfi.c.a(cxd.y, cfj -> cxe).d(2.0F).a(cbh.z));
	}

	private static boolean a(cfj cfj, bpg bpg, fu fu) {
		return true;
	}

	private static boolean b(cfj cfj, bpg bpg, fu fu) {
		return false;
	}

	private static cbl b(bje bje) {
		return new cbl(bje, cfi.c.a(cxd.E, bje).d(0.3F).a(cbh.g).b().a(bvs::a).a(bvs::b).b(bvs::b).c(bvs::b));
	}

	private static bza b() {
		return new bza(cfi.c.a(cxd.D).d(0.2F).d().a(cbh.c).b().a(bvs::c).b(bvs::b).c(bvs::b));
	}

	private static cav a(bje bje, cfi.c c) {
		cfi.e e3 = (cfj, bpg, fu) -> {
			cdl cdl4 = bpg.c(fu);
			if (!(cdl4 instanceof ceg)) {
				return true;
			} else {
				ceg ceg5 = (ceg)cdl4;
				return ceg5.l();
			}
		};
		return new cav(bje, c.d(2.0F).e().b().b(e3).c(e3));
	}

	private static cfc a(boolean boolean1) {
		cfi.e e2 = (cfj, bpg, fu) -> !(Boolean)cfj.c(cfc.b);
		return new cfc(boolean1, cfi.c.a(cxd.M).d(1.5F).a(bvs::b).b(e2).c(e2));
	}

	private static bvr a(String string, bvr bvr) {
		return gl.a(gl.aj, string, bvr);
	}

	public static void a() {
		bvr.m.forEach(cfi.a::a);
	}

	static {
		for (bvr bvr2 : gl.aj) {
			for (cfj cfj4 : bvr2.m().a()) {
				bvr.m.b(cfj4);
			}

			bvr2.r();
		}
	}
}
