java.lang.NullPointerException: Cannot invoke "cuchaz.enigma.source.vineflower.VineflowerTextTokenCollector.accept(cuchaz.enigma.source.SourceIndex)" because the return value of "java.util.concurrent.atomic.AtomicReference.get()" is null
	at cuchaz.enigma.source.vineflower.VineflowerSource.ensureDecompiled(VineflowerSource.java:88)
	at cuchaz.enigma.source.vineflower.VineflowerSource.asString(VineflowerSource.java:38)
	at cuchaz.enigma.EnigmaProject$JarExport.decompileClass(EnigmaProject.java:322)
	at cuchaz.enigma.EnigmaProject$JarExport.lambda$decompileStream$1(EnigmaProject.java:297)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:759)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
